// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from './client'
import { client } from './client.gen'
import {
  assignConversationResponseTransformer,
  blockContactResponseTransformer,
  checkWhatsappHealthResponseTransformer,
  closeConversationResponseTransformer,
  createWhatsappTemplateDraftResponseTransformer,
  deleteWhatsappTemplateRemoteResponseTransformer,
  duplicateWhatsappTemplateResponseTransformer,
  getContactResponseTransformer,
  getConversationResponseTransformer,
  getWhatsappConnectionResponseTransformer,
  getWhatsappTemplateResponseTransformer,
  listContactsResponseTransformer,
  listConversationsResponseTransformer,
  listMembersResponseTransformer,
  listMessagesResponseTransformer,
  listUsersResponseTransformer,
  listWhatsappTemplateRevisionsResponseTransformer,
  listWhatsappTemplatesResponseTransformer,
  markConversationReadResponseTransformer,
  reopenConversationResponseTransformer,
  sendMessageResponseTransformer,
  sendTemplateMessageResponseTransformer,
  startConversationResponseTransformer,
  submitWhatsappTemplateResponseTransformer,
  unassignConversationResponseTransformer,
  updateContactResponseTransformer,
  updateConversationResponseTransformer,
  updateWhatsappConnectionResponseTransformer,
  updateWhatsappTemplateDraftResponseTransformer,
} from './transformers.gen'
import type {
  AssignConversationData,
  AssignConversationResponses,
  BlockContactData,
  BlockContactResponses,
  CheckWhatsappHealthData,
  CheckWhatsappHealthResponses,
  CloseConversationData,
  CloseConversationResponses,
  ConfirmWhatsappTemplateAssetUploadData,
  ConfirmWhatsappTemplateAssetUploadResponses,
  CreateWhatsappTemplateDraftData,
  CreateWhatsappTemplateDraftResponses,
  DeleteWhatsappConnectionData,
  DeleteWhatsappConnectionResponses,
  DeleteWhatsappTemplateDraftData,
  DeleteWhatsappTemplateDraftResponses,
  DeleteWhatsappTemplateRemoteData,
  DeleteWhatsappTemplateRemoteResponses,
  DuplicateWhatsappTemplateData,
  DuplicateWhatsappTemplateResponses,
  GetContactData,
  GetContactResponses,
  GetConversationData,
  GetConversationResponses,
  GetReportsOverviewData,
  GetReportsOverviewResponses,
  GetWhatsappConnectionData,
  GetWhatsappConnectionResponses,
  GetWhatsappReadinessData,
  GetWhatsappReadinessResponses,
  GetWhatsappTemplateAssetPreviewData,
  GetWhatsappTemplateAssetPreviewResponses,
  GetWhatsappTemplateData,
  GetWhatsappTemplateResponses,
  HealthCheckData,
  HealthCheckErrors,
  HealthCheckResponses,
  ListAgentPerformanceData,
  ListAgentPerformanceResponses,
  ListContactsData,
  ListContactsResponses,
  ListConversationsData,
  ListConversationsResponses,
  ListMembersData,
  ListMembersResponses,
  ListMessagesData,
  ListMessagesResponses,
  ListUsersData,
  ListUsersResponses,
  ListWhatsappLogsData,
  ListWhatsappLogsResponses,
  ListWhatsappPhoneNumbersData,
  ListWhatsappPhoneNumbersResponses,
  ListWhatsappTemplateRevisionsData,
  ListWhatsappTemplateRevisionsResponses,
  ListWhatsappTemplatesData,
  ListWhatsappTemplatesResponses,
  LivenessProbeData,
  LivenessProbeResponses,
  MarkConversationReadData,
  MarkConversationReadResponses,
  PrepareWhatsappTemplateAssetUploadData,
  PrepareWhatsappTemplateAssetUploadResponses,
  ReadinessProbeData,
  ReadinessProbeErrors,
  ReadinessProbeResponses,
  ReceiveWhatsappWebhookData,
  ReceiveWhatsappWebhookResponses,
  RegisterWhatsappNumberData,
  RegisterWhatsappNumberResponses,
  ReopenConversationData,
  ReopenConversationResponses,
  SendMessageData,
  SendMessageResponses,
  SendTemplateMessageData,
  SendTemplateMessageResponses,
  SendWhatsappTestMessageData,
  SendWhatsappTestMessageResponses,
  StartConversationData,
  StartConversationResponses,
  SubmitWhatsappTemplateData,
  SubmitWhatsappTemplateResponses,
  SubscribeWhatsappAppData,
  SubscribeWhatsappAppResponses,
  SyncWhatsappTemplatesData,
  SyncWhatsappTemplatesResponses,
  UnassignConversationData,
  UnassignConversationResponses,
  UpdateContactData,
  UpdateContactResponses,
  UpdateConversationData,
  UpdateConversationResponses,
  UpdateWhatsappConnectionData,
  UpdateWhatsappConnectionResponses,
  UpdateWhatsappTemplateDraftData,
  UpdateWhatsappTemplateDraftResponses,
  ValidateWhatsappTemplateRevisionData,
  ValidateWhatsappTemplateRevisionResponses,
  VerifyWhatsappWebhookData,
  VerifyWhatsappWebhookResponses,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

/**
 * Health check
 */
export const healthCheck = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCheckData, ThrowOnError>,
): RequestResult<HealthCheckResponses, HealthCheckErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    HealthCheckResponses,
    HealthCheckErrors,
    ThrowOnError
  >({ url: '/health', ...options })

/**
 * Liveness probe (process alive)
 */
export const livenessProbe = <ThrowOnError extends boolean = false>(
  options?: Options<LivenessProbeData, ThrowOnError>,
): RequestResult<LivenessProbeResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    LivenessProbeResponses,
    unknown,
    ThrowOnError
  >({ url: '/health/live', ...options })

/**
 * Readiness probe (dependencies healthy)
 */
export const readinessProbe = <ThrowOnError extends boolean = false>(
  options?: Options<ReadinessProbeData, ThrowOnError>,
): RequestResult<ReadinessProbeResponses, ReadinessProbeErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ReadinessProbeResponses,
    ReadinessProbeErrors,
    ThrowOnError
  >({ url: '/health/ready', ...options })

/**
 * Lista contatos visíveis para o solicitante
 */
export const listContacts = <ThrowOnError extends boolean = false>(
  options?: Options<ListContactsData, ThrowOnError>,
): RequestResult<ListContactsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<ListContactsResponses, unknown, ThrowOnError>(
    {
      responseTransformer: listContactsResponseTransformer,
      url: '/contacts/',
      ...options,
    },
  )

/**
 * Detalha um contato com as conversas recentes dele
 */
export const getContact = <ThrowOnError extends boolean = false>(
  options: Options<GetContactData, ThrowOnError>,
): RequestResult<GetContactResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<GetContactResponses, unknown, ThrowOnError>({
    responseTransformer: getContactResponseTransformer,
    url: '/contacts/{id}',
    ...options,
  })

/**
 * Atualiza os dados editáveis do contato
 */
export const updateContact = <ThrowOnError extends boolean = false>(
  options: Options<UpdateContactData, ThrowOnError>,
): RequestResult<UpdateContactResponses, unknown, ThrowOnError> =>
  (options.client ?? client).patch<
    UpdateContactResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: updateContactResponseTransformer,
    url: '/contacts/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Bloqueia ou desbloqueia o contato
 */
export const blockContact = <ThrowOnError extends boolean = false>(
  options: Options<BlockContactData, ThrowOnError>,
): RequestResult<BlockContactResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<BlockContactResponses, unknown, ThrowOnError>(
    {
      responseTransformer: blockContactResponseTransformer,
      url: '/contacts/{id}/block',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    },
  )

/**
 * Lista conversas visíveis para o solicitante
 */
export const listConversations = <ThrowOnError extends boolean = false>(
  options?: Options<ListConversationsData, ThrowOnError>,
): RequestResult<ListConversationsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    ListConversationsResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: listConversationsResponseTransformer,
    url: '/conversations/',
    ...options,
  })

/**
 * Detalha uma conversa com a janela de 24h calculada
 */
export const getConversation = <ThrowOnError extends boolean = false>(
  options: Options<GetConversationData, ThrowOnError>,
): RequestResult<GetConversationResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<
    GetConversationResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: getConversationResponseTransformer,
    url: '/conversations/{id}',
    ...options,
  })

/**
 * Altera a prioridade da conversa
 */
export const updateConversation = <ThrowOnError extends boolean = false>(
  options: Options<UpdateConversationData, ThrowOnError>,
): RequestResult<UpdateConversationResponses, unknown, ThrowOnError> =>
  (options.client ?? client).patch<
    UpdateConversationResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: updateConversationResponseTransformer,
    url: '/conversations/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Zera o contador de mensagens não lidas da conversa
 */
export const markConversationRead = <ThrowOnError extends boolean = false>(
  options: Options<MarkConversationReadData, ThrowOnError>,
): RequestResult<MarkConversationReadResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    MarkConversationReadResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: markConversationReadResponseTransformer,
    url: '/conversations/{id}/read',
    ...options,
  })

/**
 * Atribui a conversa a um atendente
 */
export const assignConversation = <ThrowOnError extends boolean = false>(
  options: Options<AssignConversationData, ThrowOnError>,
): RequestResult<AssignConversationResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    AssignConversationResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: assignConversationResponseTransformer,
    url: '/conversations/{id}/assign',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Remove o responsável da conversa
 */
export const unassignConversation = <ThrowOnError extends boolean = false>(
  options: Options<UnassignConversationData, ThrowOnError>,
): RequestResult<UnassignConversationResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    UnassignConversationResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: unassignConversationResponseTransformer,
    url: '/conversations/{id}/unassign',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Encerra uma conversa
 */
export const closeConversation = <ThrowOnError extends boolean = false>(
  options: Options<CloseConversationData, ThrowOnError>,
): RequestResult<CloseConversationResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    CloseConversationResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: closeConversationResponseTransformer,
    url: '/conversations/{id}/close',
    ...options,
  })

/**
 * Reabre uma conversa encerrada
 */
export const reopenConversation = <ThrowOnError extends boolean = false>(
  options: Options<ReopenConversationData, ThrowOnError>,
): RequestResult<ReopenConversationResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    ReopenConversationResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: reopenConversationResponseTransformer,
    url: '/conversations/{id}/reopen',
    ...options,
  })

/**
 * Lista as mensagens de uma conversa (paginação por cursor)
 */
export const listMessages = <ThrowOnError extends boolean = false>(
  options: Options<ListMessagesData, ThrowOnError>,
): RequestResult<ListMessagesResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<ListMessagesResponses, unknown, ThrowOnError>({
    responseTransformer: listMessagesResponseTransformer,
    url: '/conversations/{id}/messages',
    ...options,
  })

/**
 * Envia uma mensagem de texto na conversa
 */
export const sendMessage = <ThrowOnError extends boolean = false>(
  options: Options<SendMessageData, ThrowOnError>,
): RequestResult<SendMessageResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<SendMessageResponses, unknown, ThrowOnError>({
    responseTransformer: sendMessageResponseTransformer,
    url: '/conversations/{id}/messages',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Envia uma mensagem de modelo (válida fora da janela de 24h)
 */
export const sendTemplateMessage = <ThrowOnError extends boolean = false>(
  options: Options<SendTemplateMessageData, ThrowOnError>,
): RequestResult<SendTemplateMessageResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    SendTemplateMessageResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: sendTemplateMessageResponseTransformer,
    url: '/conversations/{id}/messages/template',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Inicia uma conversa com um número novo via modelo (template)
 */
export const startConversation = <ThrowOnError extends boolean = false>(
  options: Options<StartConversationData, ThrowOnError>,
): RequestResult<StartConversationResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    StartConversationResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: startConversationResponseTransformer,
    url: '/conversations/start',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * List users
 */
export const listMembers = <ThrowOnError extends boolean = false>(
  options?: Options<ListMembersData, ThrowOnError>,
): RequestResult<ListMembersResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<ListMembersResponses, unknown, ThrowOnError>({
    responseTransformer: listMembersResponseTransformer,
    url: '/members/',
    ...options,
  })

/**
 * Resumo do atendimento no período
 *
 * Totais, médias e séries da conta ativa. A coorte de conversas é a criada no período — `conversationsOpen/Pending/Closed` e `statusBreakdown` são a mesma contagem por status atual, e somam `conversationsStarted`. `resolutionSeconds` é a exceção: usa as conversas fechadas dentro do período. As séries cobrem todos os dias do intervalo e o heatmap todas as 168 células, no fuso America/Sao_Paulo; `heatmap.count` soma mensagens recebidas e enviadas. Vendedor e somente-leitura são sempre restritos às próprias conversas.
 */
export const getReportsOverview = <ThrowOnError extends boolean = false>(
  options: Options<GetReportsOverviewData, ThrowOnError>,
): RequestResult<GetReportsOverviewResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<
    GetReportsOverviewResponses,
    unknown,
    ThrowOnError
  >({ url: '/reports/overview', ...options })

/**
 * Desempenho por atendente no período
 *
 * Uma linha por membro da equipe (todo papel diferente de `user`), inclusive quem não teve atividade. `assigned` conta as conversas atribuídas no período pelo histórico e `open` quantas delas seguem abertas com ele; `closed` e `resolutionSeconds` usam as conversas que ele fechou no período; `firstResponseSeconds` mede a primeira resposta dele à primeira mensagem do contato. Restrito a admin e gestor.
 */
export const listAgentPerformance = <ThrowOnError extends boolean = false>(
  options: Options<ListAgentPerformanceData, ThrowOnError>,
): RequestResult<ListAgentPerformanceResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<
    ListAgentPerformanceResponses,
    unknown,
    ThrowOnError
  >({ url: '/reports/agents', ...options })

/**
 * List users
 */
export const listUsers = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersData, ThrowOnError>,
): RequestResult<ListUsersResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<ListUsersResponses, unknown, ThrowOnError>({
    responseTransformer: listUsersResponseTransformer,
    url: '/users/',
    ...options,
  })

/**
 * Handshake de verificação do webhook do WhatsApp
 */
export const verifyWhatsappWebhook = <ThrowOnError extends boolean = false>(
  options?: Options<VerifyWhatsappWebhookData, ThrowOnError>,
): RequestResult<VerifyWhatsappWebhookResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    VerifyWhatsappWebhookResponses,
    unknown,
    ThrowOnError
  >({ url: '/webhooks/whatsapp', ...options })

/**
 * Ingestão de eventos do webhook do WhatsApp
 */
export const receiveWhatsappWebhook = <ThrowOnError extends boolean = false>(
  options?: Options<ReceiveWhatsappWebhookData, ThrowOnError>,
): RequestResult<ReceiveWhatsappWebhookResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).post<
    ReceiveWhatsappWebhookResponses,
    unknown,
    ThrowOnError
  >({ url: '/webhooks/whatsapp', ...options })

/**
 * Remove a conexão WhatsApp
 */
export const deleteWhatsappConnection = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteWhatsappConnectionData, ThrowOnError>,
): RequestResult<DeleteWhatsappConnectionResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).delete<
    DeleteWhatsappConnectionResponses,
    unknown,
    ThrowOnError
  >({ url: '/whatsapp/', ...options })

/**
 * Estado da conexão WhatsApp (segredos mascarados)
 */
export const getWhatsappConnection = <ThrowOnError extends boolean = false>(
  options?: Options<GetWhatsappConnectionData, ThrowOnError>,
): RequestResult<GetWhatsappConnectionResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    GetWhatsappConnectionResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: getWhatsappConnectionResponseTransformer,
    url: '/whatsapp/',
    ...options,
  })

/**
 * Salva as credenciais (valida na Graph API antes de gravar)
 */
export const updateWhatsappConnection = <ThrowOnError extends boolean = false>(
  options: Options<UpdateWhatsappConnectionData, ThrowOnError>,
): RequestResult<UpdateWhatsappConnectionResponses, unknown, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateWhatsappConnectionResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: updateWhatsappConnectionResponseTransformer,
    url: '/whatsapp/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Consulta o número na Graph API (nome, qualidade e tier)
 */
export const checkWhatsappHealth = <ThrowOnError extends boolean = false>(
  options?: Options<CheckWhatsappHealthData, ThrowOnError>,
): RequestResult<CheckWhatsappHealthResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    CheckWhatsappHealthResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: checkWhatsappHealthResponseTransformer,
    url: '/whatsapp/health',
    ...options,
  })

/**
 * Diagnóstico completo do setup (roda todas as verificações)
 */
export const getWhatsappReadiness = <ThrowOnError extends boolean = false>(
  options?: Options<GetWhatsappReadinessData, ThrowOnError>,
): RequestResult<GetWhatsappReadinessResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    GetWhatsappReadinessResponses,
    unknown,
    ThrowOnError
  >({ url: '/whatsapp/readiness', ...options })

/**
 * Lista os números do WABA na Cloud API
 */
export const listWhatsappPhoneNumbers = <ThrowOnError extends boolean = false>(
  options?: Options<ListWhatsappPhoneNumbersData, ThrowOnError>,
): RequestResult<ListWhatsappPhoneNumbersResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    ListWhatsappPhoneNumbersResponses,
    unknown,
    ThrowOnError
  >({ url: '/whatsapp/phone-numbers', ...options })

/**
 * Registra o número na Cloud API com o PIN de verificação
 */
export const registerWhatsappNumber = <ThrowOnError extends boolean = false>(
  options: Options<RegisterWhatsappNumberData, ThrowOnError>,
): RequestResult<RegisterWhatsappNumberResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    RegisterWhatsappNumberResponses,
    unknown,
    ThrowOnError
  >({
    url: '/whatsapp/register-number',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Inscreve o app no WABA para receber os webhooks
 */
export const subscribeWhatsappApp = <ThrowOnError extends boolean = false>(
  options?: Options<SubscribeWhatsappAppData, ThrowOnError>,
): RequestResult<SubscribeWhatsappAppResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).post<
    SubscribeWhatsappAppResponses,
    unknown,
    ThrowOnError
  >({ url: '/whatsapp/subscribe-app', ...options })

/**
 * Envia uma mensagem de teste (texto livre ou template)
 */
export const sendWhatsappTestMessage = <ThrowOnError extends boolean = false>(
  options: Options<SendWhatsappTestMessageData, ThrowOnError>,
): RequestResult<SendWhatsappTestMessageResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    SendWhatsappTestMessageResponses,
    unknown,
    ThrowOnError
  >({
    url: '/whatsapp/test-message',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Histórico do console de webhooks (seed do stream)
 */
export const listWhatsappLogs = <ThrowOnError extends boolean = false>(
  options?: Options<ListWhatsappLogsData, ThrowOnError>,
): RequestResult<ListWhatsappLogsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    ListWhatsappLogsResponses,
    unknown,
    ThrowOnError
  >({ url: '/whatsapp/logs', ...options })

/**
 * Lista os modelos da conta ativa com filtros e paginação
 */
export const listWhatsappTemplates = <ThrowOnError extends boolean = false>(
  options?: Options<ListWhatsappTemplatesData, ThrowOnError>,
): RequestResult<ListWhatsappTemplatesResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    ListWhatsappTemplatesResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: listWhatsappTemplatesResponseTransformer,
    url: '/whatsapp/templates/',
    ...options,
  })

/**
 * Cria um modelo com a primeira revisão em rascunho
 */
export const createWhatsappTemplateDraft = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateWhatsappTemplateDraftData, ThrowOnError>,
): RequestResult<CreateWhatsappTemplateDraftResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    CreateWhatsappTemplateDraftResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: createWhatsappTemplateDraftResponseTransformer,
    url: '/whatsapp/templates/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Apaga o rascunho (e o modelo, quando nunca foi enviado)
 */
export const deleteWhatsappTemplateDraft = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteWhatsappTemplateDraftData, ThrowOnError>,
): RequestResult<DeleteWhatsappTemplateDraftResponses, unknown, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteWhatsappTemplateDraftResponses,
    unknown,
    ThrowOnError
  >({ url: '/whatsapp/templates/{id}', ...options })

/**
 * Detalha um modelo com a definição mais recente
 */
export const getWhatsappTemplate = <ThrowOnError extends boolean = false>(
  options: Options<GetWhatsappTemplateData, ThrowOnError>,
): RequestResult<GetWhatsappTemplateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<
    GetWhatsappTemplateResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: getWhatsappTemplateResponseTransformer,
    url: '/whatsapp/templates/{id}',
    ...options,
  })

/**
 * Edita o rascunho com trava otimista de versão
 */
export const updateWhatsappTemplateDraft = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateWhatsappTemplateDraftData, ThrowOnError>,
): RequestResult<UpdateWhatsappTemplateDraftResponses, unknown, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateWhatsappTemplateDraftResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: updateWhatsappTemplateDraftResponseTransformer,
    url: '/whatsapp/templates/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Histórico de revisões do modelo, da mais nova para a antiga
 */
export const listWhatsappTemplateRevisions = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListWhatsappTemplateRevisionsData, ThrowOnError>,
): RequestResult<
  ListWhatsappTemplateRevisionsResponses,
  unknown,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListWhatsappTemplateRevisionsResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: listWhatsappTemplateRevisionsResponseTransformer,
    url: '/whatsapp/templates/{id}/revisions',
    ...options,
  })

/**
 * Duplica o modelo em um novo rascunho com outro nome
 */
export const duplicateWhatsappTemplate = <ThrowOnError extends boolean = false>(
  options: Options<DuplicateWhatsappTemplateData, ThrowOnError>,
): RequestResult<DuplicateWhatsappTemplateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    DuplicateWhatsappTemplateResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: duplicateWhatsappTemplateResponseTransformer,
    url: '/whatsapp/templates/{id}/duplicate',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Valida uma definição sem gravar nada
 */
export const validateWhatsappTemplateRevision = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ValidateWhatsappTemplateRevisionData, ThrowOnError>,
): RequestResult<
  ValidateWhatsappTemplateRevisionResponses,
  unknown,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ValidateWhatsappTemplateRevisionResponses,
    unknown,
    ThrowOnError
  >({
    url: '/whatsapp/templates/validate',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Envia o rascunho para aprovação da Meta
 */
export const submitWhatsappTemplate = <ThrowOnError extends boolean = false>(
  options: Options<SubmitWhatsappTemplateData, ThrowOnError>,
): RequestResult<SubmitWhatsappTemplateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    SubmitWhatsappTemplateResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: submitWhatsappTemplateResponseTransformer,
    url: '/whatsapp/templates/{id}/submit',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Espelha o catálogo da Meta sem tocar nos rascunhos locais
 */
export const syncWhatsappTemplates = <ThrowOnError extends boolean = false>(
  options?: Options<SyncWhatsappTemplatesData, ThrowOnError>,
): RequestResult<SyncWhatsappTemplatesResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).post<
    SyncWhatsappTemplatesResponses,
    unknown,
    ThrowOnError
  >({ url: '/whatsapp/templates/sync', ...options })

/**
 * Apaga o modelo na Meta e zera o espelho remoto local
 */
export const deleteWhatsappTemplateRemote = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteWhatsappTemplateRemoteData, ThrowOnError>,
): RequestResult<
  DeleteWhatsappTemplateRemoteResponses,
  unknown,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteWhatsappTemplateRemoteResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: deleteWhatsappTemplateRemoteResponseTransformer,
    url: '/whatsapp/templates/{id}/remote',
    ...options,
  })

/**
 * Abre um upload assinado no bucket privado para a mídia
 */
export const prepareWhatsappTemplateAssetUpload = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PrepareWhatsappTemplateAssetUploadData, ThrowOnError>,
): RequestResult<
  PrepareWhatsappTemplateAssetUploadResponses,
  unknown,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PrepareWhatsappTemplateAssetUploadResponses,
    unknown,
    ThrowOnError
  >({
    url: '/whatsapp/templates/assets/prepare',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Confere o arquivo enviado e gera o handle de upload da Meta
 */
export const confirmWhatsappTemplateAssetUpload = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ConfirmWhatsappTemplateAssetUploadData, ThrowOnError>,
): RequestResult<
  ConfirmWhatsappTemplateAssetUploadResponses,
  unknown,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ConfirmWhatsappTemplateAssetUploadResponses,
    unknown,
    ThrowOnError
  >({ url: '/whatsapp/templates/assets/{assetId}/confirm', ...options })

/**
 * Devolve uma URL assinada curta para pré-visualizar a mídia
 */
export const getWhatsappTemplateAssetPreview = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetWhatsappTemplateAssetPreviewData, ThrowOnError>,
): RequestResult<
  GetWhatsappTemplateAssetPreviewResponses,
  unknown,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetWhatsappTemplateAssetPreviewResponses,
    unknown,
    ThrowOnError
  >({ url: '/whatsapp/templates/assets/{assetId}/preview', ...options })
