// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from './client'
import { client } from './client.gen'
import {
  checkWhatsappHealthResponseTransformer,
  getWhatsappConnectionResponseTransformer,
  listMembersResponseTransformer,
  listUsersResponseTransformer,
  updateWhatsappConnectionResponseTransformer,
} from './transformers.gen'
import type {
  CheckWhatsappHealthData,
  CheckWhatsappHealthResponses,
  DeleteWhatsappConnectionData,
  DeleteWhatsappConnectionResponses,
  GetWhatsappConnectionData,
  GetWhatsappConnectionResponses,
  HealthCheckData,
  HealthCheckErrors,
  HealthCheckResponses,
  ListMembersData,
  ListMembersResponses,
  ListUsersData,
  ListUsersResponses,
  ListWhatsappLogsData,
  ListWhatsappLogsResponses,
  LivenessProbeData,
  LivenessProbeResponses,
  ReadinessProbeData,
  ReadinessProbeErrors,
  ReadinessProbeResponses,
  ReceiveWhatsappWebhookData,
  ReceiveWhatsappWebhookResponses,
  SendWhatsappTestMessageData,
  SendWhatsappTestMessageResponses,
  UpdateWhatsappConnectionData,
  UpdateWhatsappConnectionResponses,
  VerifyWhatsappWebhookData,
  VerifyWhatsappWebhookResponses,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

/**
 * Health check
 */
export const healthCheck = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCheckData, ThrowOnError>,
): RequestResult<HealthCheckResponses, HealthCheckErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    HealthCheckResponses,
    HealthCheckErrors,
    ThrowOnError
  >({ url: '/health', ...options })

/**
 * Liveness probe (process alive)
 */
export const livenessProbe = <ThrowOnError extends boolean = false>(
  options?: Options<LivenessProbeData, ThrowOnError>,
): RequestResult<LivenessProbeResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    LivenessProbeResponses,
    unknown,
    ThrowOnError
  >({ url: '/health/live', ...options })

/**
 * Readiness probe (dependencies healthy)
 */
export const readinessProbe = <ThrowOnError extends boolean = false>(
  options?: Options<ReadinessProbeData, ThrowOnError>,
): RequestResult<ReadinessProbeResponses, ReadinessProbeErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ReadinessProbeResponses,
    ReadinessProbeErrors,
    ThrowOnError
  >({ url: '/health/ready', ...options })

/**
 * List users
 */
export const listMembers = <ThrowOnError extends boolean = false>(
  options?: Options<ListMembersData, ThrowOnError>,
): RequestResult<ListMembersResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<ListMembersResponses, unknown, ThrowOnError>({
    responseTransformer: listMembersResponseTransformer,
    url: '/members/',
    ...options,
  })

/**
 * List users
 */
export const listUsers = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersData, ThrowOnError>,
): RequestResult<ListUsersResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<ListUsersResponses, unknown, ThrowOnError>({
    responseTransformer: listUsersResponseTransformer,
    url: '/users/',
    ...options,
  })

/**
 * Handshake de verificação do webhook do WhatsApp
 */
export const verifyWhatsappWebhook = <ThrowOnError extends boolean = false>(
  options?: Options<VerifyWhatsappWebhookData, ThrowOnError>,
): RequestResult<VerifyWhatsappWebhookResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    VerifyWhatsappWebhookResponses,
    unknown,
    ThrowOnError
  >({ url: '/webhooks/whatsapp', ...options })

/**
 * Ingestão de eventos do webhook do WhatsApp
 */
export const receiveWhatsappWebhook = <ThrowOnError extends boolean = false>(
  options?: Options<ReceiveWhatsappWebhookData, ThrowOnError>,
): RequestResult<ReceiveWhatsappWebhookResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).post<
    ReceiveWhatsappWebhookResponses,
    unknown,
    ThrowOnError
  >({ url: '/webhooks/whatsapp', ...options })

/**
 * Remove a conexão WhatsApp
 */
export const deleteWhatsappConnection = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteWhatsappConnectionData, ThrowOnError>,
): RequestResult<DeleteWhatsappConnectionResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).delete<
    DeleteWhatsappConnectionResponses,
    unknown,
    ThrowOnError
  >({ url: '/whatsapp/', ...options })

/**
 * Estado da conexão WhatsApp (segredos mascarados)
 */
export const getWhatsappConnection = <ThrowOnError extends boolean = false>(
  options?: Options<GetWhatsappConnectionData, ThrowOnError>,
): RequestResult<GetWhatsappConnectionResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    GetWhatsappConnectionResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: getWhatsappConnectionResponseTransformer,
    url: '/whatsapp/',
    ...options,
  })

/**
 * Salva as credenciais (valida na Graph API antes de gravar)
 */
export const updateWhatsappConnection = <ThrowOnError extends boolean = false>(
  options: Options<UpdateWhatsappConnectionData, ThrowOnError>,
): RequestResult<UpdateWhatsappConnectionResponses, unknown, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateWhatsappConnectionResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: updateWhatsappConnectionResponseTransformer,
    url: '/whatsapp/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Consulta o número na Graph API (nome, qualidade e tier)
 */
export const checkWhatsappHealth = <ThrowOnError extends boolean = false>(
  options?: Options<CheckWhatsappHealthData, ThrowOnError>,
): RequestResult<CheckWhatsappHealthResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    CheckWhatsappHealthResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: checkWhatsappHealthResponseTransformer,
    url: '/whatsapp/health',
    ...options,
  })

/**
 * Envia uma mensagem de texto de teste
 */
export const sendWhatsappTestMessage = <ThrowOnError extends boolean = false>(
  options: Options<SendWhatsappTestMessageData, ThrowOnError>,
): RequestResult<SendWhatsappTestMessageResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    SendWhatsappTestMessageResponses,
    unknown,
    ThrowOnError
  >({
    url: '/whatsapp/test-message',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Histórico do console de webhooks (seed do stream)
 */
export const listWhatsappLogs = <ThrowOnError extends boolean = false>(
  options?: Options<ListWhatsappLogsData, ThrowOnError>,
): RequestResult<ListWhatsappLogsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    ListWhatsappLogsResponses,
    unknown,
    ThrowOnError
  >({ url: '/whatsapp/logs', ...options })
