// This file is auto-generated by @hey-api/openapi-ts

import type {
  CheckWhatsappHealthResponse,
  GetWhatsappConnectionResponse,
  ListMembersResponse,
  ListUsersResponse,
  UpdateWhatsappConnectionResponse,
} from './types.gen'

export const listMembersResponseTransformer = async (
  data: any,
): Promise<ListMembersResponse> => {
  data = data.map((item: any) => {
    item.createdAt = new Date(item.createdAt)
    return item
  })
  return data
}

export const listUsersResponseTransformer = async (
  data: any,
): Promise<ListUsersResponse> => {
  data.data = data.data.map((item: any) => {
    item.createdAt = new Date(item.createdAt)
    return item
  })
  return data
}

export const getWhatsappConnectionResponseTransformer = async (
  data: any,
): Promise<GetWhatsappConnectionResponse> => {
  if (data.connection) {
    if (data.connection.lastCheckedAt) {
      data.connection.lastCheckedAt = new Date(data.connection.lastCheckedAt)
    }
  }
  return data
}

export const updateWhatsappConnectionResponseTransformer = async (
  data: any,
): Promise<UpdateWhatsappConnectionResponse> => {
  if (data.connection) {
    if (data.connection.lastCheckedAt) {
      data.connection.lastCheckedAt = new Date(data.connection.lastCheckedAt)
    }
  }
  return data
}

export const checkWhatsappHealthResponseTransformer = async (
  data: any,
): Promise<CheckWhatsappHealthResponse> => {
  data.checkedAt = new Date(data.checkedAt)
  return data
}
