// This file is auto-generated by @hey-api/openapi-ts

import type {
  BlockContactResponse,
  CheckWhatsappHealthResponse,
  GetContactResponse,
  GetConversationResponse,
  GetWhatsappConnectionResponse,
  ListContactsResponse,
  ListConversationsResponse,
  ListMembersResponse,
  ListMessagesResponse,
  ListUsersResponse,
  MarkConversationReadResponse,
  SendMessageResponse,
  SendTemplateMessageResponse,
  StartConversationResponse,
  UpdateContactResponse,
  UpdateWhatsappConnectionResponse,
} from './types.gen'

export const listContactsResponseTransformer = async (
  data: any,
): Promise<ListContactsResponse> => {
  data.data = data.data.map((item: any) => {
    item.createdAt = new Date(item.createdAt)
    item.updatedAt = new Date(item.updatedAt)
    if (item.lastInteractionAt) {
      item.lastInteractionAt = new Date(item.lastInteractionAt)
    }
    return item
  })
  return data
}

export const getContactResponseTransformer = async (
  data: any,
): Promise<GetContactResponse> => {
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  if (data.lastInteractionAt) {
    data.lastInteractionAt = new Date(data.lastInteractionAt)
  }
  data.conversations = data.conversations.map((item: any) => {
    if (item.lastMessageAt) {
      item.lastMessageAt = new Date(item.lastMessageAt)
    }
    return item
  })
  return data
}

export const updateContactResponseTransformer = async (
  data: any,
): Promise<UpdateContactResponse> => {
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  if (data.lastInteractionAt) {
    data.lastInteractionAt = new Date(data.lastInteractionAt)
  }
  return data
}

export const blockContactResponseTransformer = async (
  data: any,
): Promise<BlockContactResponse> => {
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  if (data.lastInteractionAt) {
    data.lastInteractionAt = new Date(data.lastInteractionAt)
  }
  return data
}

export const listConversationsResponseTransformer = async (
  data: any,
): Promise<ListConversationsResponse> => {
  data.data = data.data.map((item: any) => {
    if (item.lastMessageAt) {
      item.lastMessageAt = new Date(item.lastMessageAt)
    }
    if (item.lastInboundAt) {
      item.lastInboundAt = new Date(item.lastInboundAt)
    }
    if (item.assignedAt) {
      item.assignedAt = new Date(item.assignedAt)
    }
    if (item.closedAt) {
      item.closedAt = new Date(item.closedAt)
    }
    item.createdAt = new Date(item.createdAt)
    item.updatedAt = new Date(item.updatedAt)
    return item
  })
  return data
}

export const getConversationResponseTransformer = async (
  data: any,
): Promise<GetConversationResponse> => {
  if (data.lastMessageAt) {
    data.lastMessageAt = new Date(data.lastMessageAt)
  }
  if (data.lastInboundAt) {
    data.lastInboundAt = new Date(data.lastInboundAt)
  }
  if (data.assignedAt) {
    data.assignedAt = new Date(data.assignedAt)
  }
  if (data.closedAt) {
    data.closedAt = new Date(data.closedAt)
  }
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  if (data.windowExpiresAt) {
    data.windowExpiresAt = new Date(data.windowExpiresAt)
  }
  return data
}

export const markConversationReadResponseTransformer = async (
  data: any,
): Promise<MarkConversationReadResponse> => {
  if (data.lastMessageAt) {
    data.lastMessageAt = new Date(data.lastMessageAt)
  }
  if (data.lastInboundAt) {
    data.lastInboundAt = new Date(data.lastInboundAt)
  }
  if (data.assignedAt) {
    data.assignedAt = new Date(data.assignedAt)
  }
  if (data.closedAt) {
    data.closedAt = new Date(data.closedAt)
  }
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  return data
}

export const listMessagesResponseTransformer = async (
  data: any,
): Promise<ListMessagesResponse> => {
  data.data = data.data.map((item: any) => {
    if (item.waTimestamp) {
      item.waTimestamp = new Date(item.waTimestamp)
    }
    if (item.deliveredAt) {
      item.deliveredAt = new Date(item.deliveredAt)
    }
    if (item.readAt) {
      item.readAt = new Date(item.readAt)
    }
    if (item.failedAt) {
      item.failedAt = new Date(item.failedAt)
    }
    item.createdAt = new Date(item.createdAt)
    item.updatedAt = new Date(item.updatedAt)
    return item
  })
  return data
}

export const sendMessageResponseTransformer = async (
  data: any,
): Promise<SendMessageResponse> => {
  if (data.waTimestamp) {
    data.waTimestamp = new Date(data.waTimestamp)
  }
  if (data.deliveredAt) {
    data.deliveredAt = new Date(data.deliveredAt)
  }
  if (data.readAt) {
    data.readAt = new Date(data.readAt)
  }
  if (data.failedAt) {
    data.failedAt = new Date(data.failedAt)
  }
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  return data
}

export const sendTemplateMessageResponseTransformer = async (
  data: any,
): Promise<SendTemplateMessageResponse> => {
  if (data.waTimestamp) {
    data.waTimestamp = new Date(data.waTimestamp)
  }
  if (data.deliveredAt) {
    data.deliveredAt = new Date(data.deliveredAt)
  }
  if (data.readAt) {
    data.readAt = new Date(data.readAt)
  }
  if (data.failedAt) {
    data.failedAt = new Date(data.failedAt)
  }
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  return data
}

export const startConversationResponseTransformer = async (
  data: any,
): Promise<StartConversationResponse> => {
  if (data.conversation.lastMessageAt) {
    data.conversation.lastMessageAt = new Date(data.conversation.lastMessageAt)
  }
  if (data.conversation.lastInboundAt) {
    data.conversation.lastInboundAt = new Date(data.conversation.lastInboundAt)
  }
  if (data.conversation.assignedAt) {
    data.conversation.assignedAt = new Date(data.conversation.assignedAt)
  }
  if (data.conversation.closedAt) {
    data.conversation.closedAt = new Date(data.conversation.closedAt)
  }
  data.conversation.createdAt = new Date(data.conversation.createdAt)
  data.conversation.updatedAt = new Date(data.conversation.updatedAt)
  return data
}

export const listMembersResponseTransformer = async (
  data: any,
): Promise<ListMembersResponse> => {
  data = data.map((item: any) => {
    item.createdAt = new Date(item.createdAt)
    return item
  })
  return data
}

export const listUsersResponseTransformer = async (
  data: any,
): Promise<ListUsersResponse> => {
  data.data = data.data.map((item: any) => {
    item.createdAt = new Date(item.createdAt)
    return item
  })
  return data
}

export const getWhatsappConnectionResponseTransformer = async (
  data: any,
): Promise<GetWhatsappConnectionResponse> => {
  if (data.connection) {
    if (data.connection.lastCheckedAt) {
      data.connection.lastCheckedAt = new Date(data.connection.lastCheckedAt)
    }
  }
  return data
}

export const updateWhatsappConnectionResponseTransformer = async (
  data: any,
): Promise<UpdateWhatsappConnectionResponse> => {
  if (data.connection) {
    if (data.connection.lastCheckedAt) {
      data.connection.lastCheckedAt = new Date(data.connection.lastCheckedAt)
    }
  }
  return data
}

export const checkWhatsappHealthResponseTransformer = async (
  data: any,
): Promise<CheckWhatsappHealthResponse> => {
  data.checkedAt = new Date(data.checkedAt)
  return data
}
