// This file is auto-generated by @hey-api/openapi-ts

import type {
  AssignConversationResponse,
  BlockContactResponse,
  CheckWhatsappHealthResponse,
  CloseConversationResponse,
  CreateWhatsappTemplateDraftResponse,
  DeleteWhatsappTemplateRemoteResponse,
  DuplicateWhatsappTemplateResponse,
  GetContactResponse,
  GetConversationResponse,
  GetWhatsappConnectionResponse,
  GetWhatsappTemplateResponse,
  ListContactsResponse,
  ListConversationsResponse,
  ListMembersResponse,
  ListMessagesResponse,
  ListUsersResponse,
  ListWhatsappTemplateRevisionsResponse,
  ListWhatsappTemplatesResponse,
  MarkConversationReadResponse,
  ReopenConversationResponse,
  SendMessageResponse,
  SendTemplateMessageResponse,
  StartConversationResponse,
  SubmitWhatsappTemplateResponse,
  UnassignConversationResponse,
  UpdateContactResponse,
  UpdateConversationResponse,
  UpdateWhatsappConnectionResponse,
  UpdateWhatsappTemplateDraftResponse,
} from './types.gen'

export const listContactsResponseTransformer = async (
  data: any,
): Promise<ListContactsResponse> => {
  data.data = data.data.map((item: any) => {
    item.createdAt = new Date(item.createdAt)
    item.updatedAt = new Date(item.updatedAt)
    if (item.lastInteractionAt) {
      item.lastInteractionAt = new Date(item.lastInteractionAt)
    }
    return item
  })
  return data
}

export const getContactResponseTransformer = async (
  data: any,
): Promise<GetContactResponse> => {
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  if (data.lastInteractionAt) {
    data.lastInteractionAt = new Date(data.lastInteractionAt)
  }
  data.conversations = data.conversations.map((item: any) => {
    if (item.lastMessageAt) {
      item.lastMessageAt = new Date(item.lastMessageAt)
    }
    return item
  })
  return data
}

export const updateContactResponseTransformer = async (
  data: any,
): Promise<UpdateContactResponse> => {
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  if (data.lastInteractionAt) {
    data.lastInteractionAt = new Date(data.lastInteractionAt)
  }
  return data
}

export const blockContactResponseTransformer = async (
  data: any,
): Promise<BlockContactResponse> => {
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  if (data.lastInteractionAt) {
    data.lastInteractionAt = new Date(data.lastInteractionAt)
  }
  return data
}

export const listConversationsResponseTransformer = async (
  data: any,
): Promise<ListConversationsResponse> => {
  data.data = data.data.map((item: any) => {
    if (item.lastMessageAt) {
      item.lastMessageAt = new Date(item.lastMessageAt)
    }
    if (item.lastInboundAt) {
      item.lastInboundAt = new Date(item.lastInboundAt)
    }
    if (item.assignedAt) {
      item.assignedAt = new Date(item.assignedAt)
    }
    if (item.closedAt) {
      item.closedAt = new Date(item.closedAt)
    }
    item.createdAt = new Date(item.createdAt)
    item.updatedAt = new Date(item.updatedAt)
    return item
  })
  return data
}

export const getConversationResponseTransformer = async (
  data: any,
): Promise<GetConversationResponse> => {
  if (data.lastMessageAt) {
    data.lastMessageAt = new Date(data.lastMessageAt)
  }
  if (data.lastInboundAt) {
    data.lastInboundAt = new Date(data.lastInboundAt)
  }
  if (data.assignedAt) {
    data.assignedAt = new Date(data.assignedAt)
  }
  if (data.closedAt) {
    data.closedAt = new Date(data.closedAt)
  }
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  if (data.windowExpiresAt) {
    data.windowExpiresAt = new Date(data.windowExpiresAt)
  }
  return data
}

export const updateConversationResponseTransformer = async (
  data: any,
): Promise<UpdateConversationResponse> => {
  if (data.lastMessageAt) {
    data.lastMessageAt = new Date(data.lastMessageAt)
  }
  if (data.lastInboundAt) {
    data.lastInboundAt = new Date(data.lastInboundAt)
  }
  if (data.assignedAt) {
    data.assignedAt = new Date(data.assignedAt)
  }
  if (data.closedAt) {
    data.closedAt = new Date(data.closedAt)
  }
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  return data
}

export const markConversationReadResponseTransformer = async (
  data: any,
): Promise<MarkConversationReadResponse> => {
  if (data.lastMessageAt) {
    data.lastMessageAt = new Date(data.lastMessageAt)
  }
  if (data.lastInboundAt) {
    data.lastInboundAt = new Date(data.lastInboundAt)
  }
  if (data.assignedAt) {
    data.assignedAt = new Date(data.assignedAt)
  }
  if (data.closedAt) {
    data.closedAt = new Date(data.closedAt)
  }
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  return data
}

export const assignConversationResponseTransformer = async (
  data: any,
): Promise<AssignConversationResponse> => {
  if (data.lastMessageAt) {
    data.lastMessageAt = new Date(data.lastMessageAt)
  }
  if (data.lastInboundAt) {
    data.lastInboundAt = new Date(data.lastInboundAt)
  }
  if (data.assignedAt) {
    data.assignedAt = new Date(data.assignedAt)
  }
  if (data.closedAt) {
    data.closedAt = new Date(data.closedAt)
  }
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  return data
}

export const unassignConversationResponseTransformer = async (
  data: any,
): Promise<UnassignConversationResponse> => {
  if (data.lastMessageAt) {
    data.lastMessageAt = new Date(data.lastMessageAt)
  }
  if (data.lastInboundAt) {
    data.lastInboundAt = new Date(data.lastInboundAt)
  }
  if (data.assignedAt) {
    data.assignedAt = new Date(data.assignedAt)
  }
  if (data.closedAt) {
    data.closedAt = new Date(data.closedAt)
  }
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  return data
}

export const closeConversationResponseTransformer = async (
  data: any,
): Promise<CloseConversationResponse> => {
  if (data.lastMessageAt) {
    data.lastMessageAt = new Date(data.lastMessageAt)
  }
  if (data.lastInboundAt) {
    data.lastInboundAt = new Date(data.lastInboundAt)
  }
  if (data.assignedAt) {
    data.assignedAt = new Date(data.assignedAt)
  }
  if (data.closedAt) {
    data.closedAt = new Date(data.closedAt)
  }
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  return data
}

export const reopenConversationResponseTransformer = async (
  data: any,
): Promise<ReopenConversationResponse> => {
  if (data.lastMessageAt) {
    data.lastMessageAt = new Date(data.lastMessageAt)
  }
  if (data.lastInboundAt) {
    data.lastInboundAt = new Date(data.lastInboundAt)
  }
  if (data.assignedAt) {
    data.assignedAt = new Date(data.assignedAt)
  }
  if (data.closedAt) {
    data.closedAt = new Date(data.closedAt)
  }
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  return data
}

export const listMessagesResponseTransformer = async (
  data: any,
): Promise<ListMessagesResponse> => {
  data.data = data.data.map((item: any) => {
    if (item.waTimestamp) {
      item.waTimestamp = new Date(item.waTimestamp)
    }
    if (item.deliveredAt) {
      item.deliveredAt = new Date(item.deliveredAt)
    }
    if (item.readAt) {
      item.readAt = new Date(item.readAt)
    }
    if (item.failedAt) {
      item.failedAt = new Date(item.failedAt)
    }
    item.createdAt = new Date(item.createdAt)
    item.updatedAt = new Date(item.updatedAt)
    return item
  })
  return data
}

export const sendMessageResponseTransformer = async (
  data: any,
): Promise<SendMessageResponse> => {
  if (data.waTimestamp) {
    data.waTimestamp = new Date(data.waTimestamp)
  }
  if (data.deliveredAt) {
    data.deliveredAt = new Date(data.deliveredAt)
  }
  if (data.readAt) {
    data.readAt = new Date(data.readAt)
  }
  if (data.failedAt) {
    data.failedAt = new Date(data.failedAt)
  }
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  return data
}

export const sendTemplateMessageResponseTransformer = async (
  data: any,
): Promise<SendTemplateMessageResponse> => {
  if (data.waTimestamp) {
    data.waTimestamp = new Date(data.waTimestamp)
  }
  if (data.deliveredAt) {
    data.deliveredAt = new Date(data.deliveredAt)
  }
  if (data.readAt) {
    data.readAt = new Date(data.readAt)
  }
  if (data.failedAt) {
    data.failedAt = new Date(data.failedAt)
  }
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  return data
}

export const startConversationResponseTransformer = async (
  data: any,
): Promise<StartConversationResponse> => {
  if (data.conversation.lastMessageAt) {
    data.conversation.lastMessageAt = new Date(data.conversation.lastMessageAt)
  }
  if (data.conversation.lastInboundAt) {
    data.conversation.lastInboundAt = new Date(data.conversation.lastInboundAt)
  }
  if (data.conversation.assignedAt) {
    data.conversation.assignedAt = new Date(data.conversation.assignedAt)
  }
  if (data.conversation.closedAt) {
    data.conversation.closedAt = new Date(data.conversation.closedAt)
  }
  data.conversation.createdAt = new Date(data.conversation.createdAt)
  data.conversation.updatedAt = new Date(data.conversation.updatedAt)
  return data
}

export const listMembersResponseTransformer = async (
  data: any,
): Promise<ListMembersResponse> => {
  data = data.map((item: any) => {
    item.createdAt = new Date(item.createdAt)
    return item
  })
  return data
}

export const listUsersResponseTransformer = async (
  data: any,
): Promise<ListUsersResponse> => {
  data.data = data.data.map((item: any) => {
    item.createdAt = new Date(item.createdAt)
    return item
  })
  return data
}

export const getWhatsappConnectionResponseTransformer = async (
  data: any,
): Promise<GetWhatsappConnectionResponse> => {
  if (data.connection) {
    if (data.connection.lastCheckedAt) {
      data.connection.lastCheckedAt = new Date(data.connection.lastCheckedAt)
    }
  }
  return data
}

export const updateWhatsappConnectionResponseTransformer = async (
  data: any,
): Promise<UpdateWhatsappConnectionResponse> => {
  if (data.connection) {
    if (data.connection.lastCheckedAt) {
      data.connection.lastCheckedAt = new Date(data.connection.lastCheckedAt)
    }
  }
  return data
}

export const checkWhatsappHealthResponseTransformer = async (
  data: any,
): Promise<CheckWhatsappHealthResponse> => {
  data.checkedAt = new Date(data.checkedAt)
  return data
}

export const listWhatsappTemplatesResponseTransformer = async (
  data: any,
): Promise<ListWhatsappTemplatesResponse> => {
  data.data = data.data.map((item: any) => {
    if (item.remoteUpdatedAt) {
      item.remoteUpdatedAt = new Date(item.remoteUpdatedAt)
    }
    if (item.lastSyncAttemptAt) {
      item.lastSyncAttemptAt = new Date(item.lastSyncAttemptAt)
    }
    item.createdAt = new Date(item.createdAt)
    item.updatedAt = new Date(item.updatedAt)
    if (item.latestRevision) {
      if (item.latestRevision.submittedAt) {
        item.latestRevision.submittedAt = new Date(
          item.latestRevision.submittedAt,
        )
      }
      item.latestRevision.createdAt = new Date(item.latestRevision.createdAt)
      item.latestRevision.updatedAt = new Date(item.latestRevision.updatedAt)
    }
    if (item.draftRevision) {
      if (item.draftRevision.submittedAt) {
        item.draftRevision.submittedAt = new Date(
          item.draftRevision.submittedAt,
        )
      }
      item.draftRevision.createdAt = new Date(item.draftRevision.createdAt)
      item.draftRevision.updatedAt = new Date(item.draftRevision.updatedAt)
    }
    if (item.submittedRevision) {
      if (item.submittedRevision.submittedAt) {
        item.submittedRevision.submittedAt = new Date(
          item.submittedRevision.submittedAt,
        )
      }
      item.submittedRevision.createdAt = new Date(
        item.submittedRevision.createdAt,
      )
      item.submittedRevision.updatedAt = new Date(
        item.submittedRevision.updatedAt,
      )
    }
    return item
  })
  return data
}

export const createWhatsappTemplateDraftResponseTransformer = async (
  data: any,
): Promise<CreateWhatsappTemplateDraftResponse> => {
  if (data.remoteUpdatedAt) {
    data.remoteUpdatedAt = new Date(data.remoteUpdatedAt)
  }
  if (data.lastSyncAttemptAt) {
    data.lastSyncAttemptAt = new Date(data.lastSyncAttemptAt)
  }
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  if (data.latestRevision) {
    if (data.latestRevision.submittedAt) {
      data.latestRevision.submittedAt = new Date(
        data.latestRevision.submittedAt,
      )
    }
    data.latestRevision.createdAt = new Date(data.latestRevision.createdAt)
    data.latestRevision.updatedAt = new Date(data.latestRevision.updatedAt)
  }
  if (data.draftRevision) {
    if (data.draftRevision.submittedAt) {
      data.draftRevision.submittedAt = new Date(data.draftRevision.submittedAt)
    }
    data.draftRevision.createdAt = new Date(data.draftRevision.createdAt)
    data.draftRevision.updatedAt = new Date(data.draftRevision.updatedAt)
  }
  if (data.submittedRevision) {
    if (data.submittedRevision.submittedAt) {
      data.submittedRevision.submittedAt = new Date(
        data.submittedRevision.submittedAt,
      )
    }
    data.submittedRevision.createdAt = new Date(
      data.submittedRevision.createdAt,
    )
    data.submittedRevision.updatedAt = new Date(
      data.submittedRevision.updatedAt,
    )
  }
  return data
}

export const getWhatsappTemplateResponseTransformer = async (
  data: any,
): Promise<GetWhatsappTemplateResponse> => {
  if (data.remoteUpdatedAt) {
    data.remoteUpdatedAt = new Date(data.remoteUpdatedAt)
  }
  if (data.lastSyncAttemptAt) {
    data.lastSyncAttemptAt = new Date(data.lastSyncAttemptAt)
  }
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  if (data.latestRevision) {
    if (data.latestRevision.submittedAt) {
      data.latestRevision.submittedAt = new Date(
        data.latestRevision.submittedAt,
      )
    }
    data.latestRevision.createdAt = new Date(data.latestRevision.createdAt)
    data.latestRevision.updatedAt = new Date(data.latestRevision.updatedAt)
  }
  if (data.draftRevision) {
    if (data.draftRevision.submittedAt) {
      data.draftRevision.submittedAt = new Date(data.draftRevision.submittedAt)
    }
    data.draftRevision.createdAt = new Date(data.draftRevision.createdAt)
    data.draftRevision.updatedAt = new Date(data.draftRevision.updatedAt)
  }
  if (data.submittedRevision) {
    if (data.submittedRevision.submittedAt) {
      data.submittedRevision.submittedAt = new Date(
        data.submittedRevision.submittedAt,
      )
    }
    data.submittedRevision.createdAt = new Date(
      data.submittedRevision.createdAt,
    )
    data.submittedRevision.updatedAt = new Date(
      data.submittedRevision.updatedAt,
    )
  }
  return data
}

export const updateWhatsappTemplateDraftResponseTransformer = async (
  data: any,
): Promise<UpdateWhatsappTemplateDraftResponse> => {
  if (data.remoteUpdatedAt) {
    data.remoteUpdatedAt = new Date(data.remoteUpdatedAt)
  }
  if (data.lastSyncAttemptAt) {
    data.lastSyncAttemptAt = new Date(data.lastSyncAttemptAt)
  }
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  if (data.latestRevision) {
    if (data.latestRevision.submittedAt) {
      data.latestRevision.submittedAt = new Date(
        data.latestRevision.submittedAt,
      )
    }
    data.latestRevision.createdAt = new Date(data.latestRevision.createdAt)
    data.latestRevision.updatedAt = new Date(data.latestRevision.updatedAt)
  }
  if (data.draftRevision) {
    if (data.draftRevision.submittedAt) {
      data.draftRevision.submittedAt = new Date(data.draftRevision.submittedAt)
    }
    data.draftRevision.createdAt = new Date(data.draftRevision.createdAt)
    data.draftRevision.updatedAt = new Date(data.draftRevision.updatedAt)
  }
  if (data.submittedRevision) {
    if (data.submittedRevision.submittedAt) {
      data.submittedRevision.submittedAt = new Date(
        data.submittedRevision.submittedAt,
      )
    }
    data.submittedRevision.createdAt = new Date(
      data.submittedRevision.createdAt,
    )
    data.submittedRevision.updatedAt = new Date(
      data.submittedRevision.updatedAt,
    )
  }
  return data
}

export const listWhatsappTemplateRevisionsResponseTransformer = async (
  data: any,
): Promise<ListWhatsappTemplateRevisionsResponse> => {
  data.data = data.data.map((item: any) => {
    if (item.submittedAt) {
      item.submittedAt = new Date(item.submittedAt)
    }
    item.createdAt = new Date(item.createdAt)
    item.updatedAt = new Date(item.updatedAt)
    return item
  })
  return data
}

export const duplicateWhatsappTemplateResponseTransformer = async (
  data: any,
): Promise<DuplicateWhatsappTemplateResponse> => {
  if (data.remoteUpdatedAt) {
    data.remoteUpdatedAt = new Date(data.remoteUpdatedAt)
  }
  if (data.lastSyncAttemptAt) {
    data.lastSyncAttemptAt = new Date(data.lastSyncAttemptAt)
  }
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  if (data.latestRevision) {
    if (data.latestRevision.submittedAt) {
      data.latestRevision.submittedAt = new Date(
        data.latestRevision.submittedAt,
      )
    }
    data.latestRevision.createdAt = new Date(data.latestRevision.createdAt)
    data.latestRevision.updatedAt = new Date(data.latestRevision.updatedAt)
  }
  if (data.draftRevision) {
    if (data.draftRevision.submittedAt) {
      data.draftRevision.submittedAt = new Date(data.draftRevision.submittedAt)
    }
    data.draftRevision.createdAt = new Date(data.draftRevision.createdAt)
    data.draftRevision.updatedAt = new Date(data.draftRevision.updatedAt)
  }
  if (data.submittedRevision) {
    if (data.submittedRevision.submittedAt) {
      data.submittedRevision.submittedAt = new Date(
        data.submittedRevision.submittedAt,
      )
    }
    data.submittedRevision.createdAt = new Date(
      data.submittedRevision.createdAt,
    )
    data.submittedRevision.updatedAt = new Date(
      data.submittedRevision.updatedAt,
    )
  }
  return data
}

export const submitWhatsappTemplateResponseTransformer = async (
  data: any,
): Promise<SubmitWhatsappTemplateResponse> => {
  if (data.template.remoteUpdatedAt) {
    data.template.remoteUpdatedAt = new Date(data.template.remoteUpdatedAt)
  }
  if (data.template.lastSyncAttemptAt) {
    data.template.lastSyncAttemptAt = new Date(data.template.lastSyncAttemptAt)
  }
  data.template.createdAt = new Date(data.template.createdAt)
  data.template.updatedAt = new Date(data.template.updatedAt)
  if (data.template.latestRevision) {
    if (data.template.latestRevision.submittedAt) {
      data.template.latestRevision.submittedAt = new Date(
        data.template.latestRevision.submittedAt,
      )
    }
    data.template.latestRevision.createdAt = new Date(
      data.template.latestRevision.createdAt,
    )
    data.template.latestRevision.updatedAt = new Date(
      data.template.latestRevision.updatedAt,
    )
  }
  if (data.template.draftRevision) {
    if (data.template.draftRevision.submittedAt) {
      data.template.draftRevision.submittedAt = new Date(
        data.template.draftRevision.submittedAt,
      )
    }
    data.template.draftRevision.createdAt = new Date(
      data.template.draftRevision.createdAt,
    )
    data.template.draftRevision.updatedAt = new Date(
      data.template.draftRevision.updatedAt,
    )
  }
  if (data.template.submittedRevision) {
    if (data.template.submittedRevision.submittedAt) {
      data.template.submittedRevision.submittedAt = new Date(
        data.template.submittedRevision.submittedAt,
      )
    }
    data.template.submittedRevision.createdAt = new Date(
      data.template.submittedRevision.createdAt,
    )
    data.template.submittedRevision.updatedAt = new Date(
      data.template.submittedRevision.updatedAt,
    )
  }
  return data
}

export const deleteWhatsappTemplateRemoteResponseTransformer = async (
  data: any,
): Promise<DeleteWhatsappTemplateRemoteResponse> => {
  if (data.remoteUpdatedAt) {
    data.remoteUpdatedAt = new Date(data.remoteUpdatedAt)
  }
  if (data.lastSyncAttemptAt) {
    data.lastSyncAttemptAt = new Date(data.lastSyncAttemptAt)
  }
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  if (data.latestRevision) {
    if (data.latestRevision.submittedAt) {
      data.latestRevision.submittedAt = new Date(
        data.latestRevision.submittedAt,
      )
    }
    data.latestRevision.createdAt = new Date(data.latestRevision.createdAt)
    data.latestRevision.updatedAt = new Date(data.latestRevision.updatedAt)
  }
  if (data.draftRevision) {
    if (data.draftRevision.submittedAt) {
      data.draftRevision.submittedAt = new Date(data.draftRevision.submittedAt)
    }
    data.draftRevision.createdAt = new Date(data.draftRevision.createdAt)
    data.draftRevision.updatedAt = new Date(data.draftRevision.updatedAt)
  }
  if (data.submittedRevision) {
    if (data.submittedRevision.submittedAt) {
      data.submittedRevision.submittedAt = new Date(
        data.submittedRevision.submittedAt,
      )
    }
    data.submittedRevision.createdAt = new Date(
      data.submittedRevision.createdAt,
    )
    data.submittedRevision.updatedAt = new Date(
      data.submittedRevision.updatedAt,
    )
  }
  return data
}
