// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {})
}

export type HealthCheckData = {
  body?: never
  path?: never
  query?: never
  url: '/health'
}

export type HealthCheckErrors = {
  /**
   * Default Response
   */
  503: {
    status: string
    db?: string
    redis?: string
  }
}

export type HealthCheckError = HealthCheckErrors[keyof HealthCheckErrors]

export type HealthCheckResponses = {
  /**
   * Default Response
   */
  200: {
    status: string
    db?: string
    redis?: string
  }
}

export type HealthCheckResponse =
  HealthCheckResponses[keyof HealthCheckResponses]

export type LivenessProbeData = {
  body?: never
  path?: never
  query?: never
  url: '/health/live'
}

export type LivenessProbeResponses = {
  /**
   * Default Response
   */
  200: {
    status: string
  }
}

export type LivenessProbeResponse =
  LivenessProbeResponses[keyof LivenessProbeResponses]

export type ReadinessProbeData = {
  body?: never
  path?: never
  query?: never
  url: '/health/ready'
}

export type ReadinessProbeErrors = {
  /**
   * Default Response
   */
  503: {
    status: string
    db?: string
    redis?: string
  }
}

export type ReadinessProbeError =
  ReadinessProbeErrors[keyof ReadinessProbeErrors]

export type ReadinessProbeResponses = {
  /**
   * Default Response
   */
  200: {
    status: string
    db?: string
    redis?: string
  }
}

export type ReadinessProbeResponse =
  ReadinessProbeResponses[keyof ReadinessProbeResponses]

export type ListMembersData = {
  body?: never
  path?: never
  query?: never
  url: '/members/'
}

export type ListMembersResponses = {
  /**
   * Default Response
   */
  200: Array<{
    id: string
    name: string | null
    email: string
    image: string | null
    role: string | null
    createdAt: Date
  }>
}

export type ListMembersResponse =
  ListMembersResponses[keyof ListMembersResponses]

export type ListUsersData = {
  body?: never
  path?: never
  query?: {
    search?: string
    role?: 'admin' | 'user'
    banned?: boolean
    isStaff?: string
    page?: number
    limit?: number
  }
  url: '/users/'
}

export type ListUsersResponses = {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      id: string
      name: string
      email: string
      image: string | null
      role: string | null
      banned: boolean | null
      emailVerified: boolean
      createdAt: Date
      phone: string | null
    }>
    meta: {
      total: number
      page: number
      limit: number
      totalPages: number
      hasNext: boolean
    }
  }
}

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses]

export type VerifyWhatsappWebhookData = {
  body?: never
  path?: never
  query?: {
    'hub.mode'?: string
    'hub.verify_token'?: string
    'hub.challenge'?: string
  }
  url: '/webhooks/whatsapp'
}

export type VerifyWhatsappWebhookResponses = {
  /**
   * Default Response
   */
  200: string
}

export type VerifyWhatsappWebhookResponse =
  VerifyWhatsappWebhookResponses[keyof VerifyWhatsappWebhookResponses]

export type ReceiveWhatsappWebhookData = {
  body?: never
  path?: never
  query?: never
  url: '/webhooks/whatsapp'
}

export type ReceiveWhatsappWebhookResponses = {
  /**
   * Default Response
   */
  200: {
    received: boolean
  }
}

export type ReceiveWhatsappWebhookResponse =
  ReceiveWhatsappWebhookResponses[keyof ReceiveWhatsappWebhookResponses]

export type DeleteWhatsappConnectionData = {
  body?: never
  path?: never
  query?: never
  url: '/whatsapp/'
}

export type DeleteWhatsappConnectionResponses = {
  /**
   * Default Response
   */
  200: {
    deleted: boolean
  }
}

export type DeleteWhatsappConnectionResponse =
  DeleteWhatsappConnectionResponses[keyof DeleteWhatsappConnectionResponses]

export type GetWhatsappConnectionData = {
  body?: never
  path?: never
  query?: never
  url: '/whatsapp/'
}

export type GetWhatsappConnectionResponses = {
  /**
   * Default Response
   */
  200: {
    configured: boolean
    connection: {
      accessToken: string
      appSecret: string
      phoneNumberId: string
      wabaId: string
      verifyToken: string
      webhookBaseUrl: string | null
      displayPhoneNumber: string | null
      verifiedName: string | null
      qualityRating: string | null
      lastCheckedAt: Date | null
    } | null
    webhookUrl: string
    encryptionConfigured: boolean
    webhookBaseIsLocal: boolean
  }
}

export type GetWhatsappConnectionResponse =
  GetWhatsappConnectionResponses[keyof GetWhatsappConnectionResponses]

export type UpdateWhatsappConnectionData = {
  body: {
    accessToken: string
    appSecret: string
    phoneNumberId: string
    wabaId: string
    verifyToken: string
    webhookBaseUrl?: string
  }
  path?: never
  query?: never
  url: '/whatsapp/'
}

export type UpdateWhatsappConnectionResponses = {
  /**
   * Default Response
   */
  200: {
    configured: boolean
    connection: {
      accessToken: string
      appSecret: string
      phoneNumberId: string
      wabaId: string
      verifyToken: string
      webhookBaseUrl: string | null
      displayPhoneNumber: string | null
      verifiedName: string | null
      qualityRating: string | null
      lastCheckedAt: Date | null
    } | null
    webhookUrl: string
    encryptionConfigured: boolean
    webhookBaseIsLocal: boolean
  }
}

export type UpdateWhatsappConnectionResponse =
  UpdateWhatsappConnectionResponses[keyof UpdateWhatsappConnectionResponses]

export type CheckWhatsappHealthData = {
  body?: never
  path?: never
  query?: never
  url: '/whatsapp/health'
}

export type CheckWhatsappHealthResponses = {
  /**
   * Default Response
   */
  200: {
    id: string
    displayPhoneNumber: string | null
    verifiedName: string | null
    qualityRating: string | null
    messagingLimitTier: string | null
    checkedAt: Date
  }
}

export type CheckWhatsappHealthResponse =
  CheckWhatsappHealthResponses[keyof CheckWhatsappHealthResponses]

export type SendWhatsappTestMessageData = {
  body: {
    to: string
    text: string
  }
  path?: never
  query?: never
  url: '/whatsapp/test-message'
}

export type SendWhatsappTestMessageResponses = {
  /**
   * Default Response
   */
  200: {
    messageId: string
  }
}

export type SendWhatsappTestMessageResponse =
  SendWhatsappTestMessageResponses[keyof SendWhatsappTestMessageResponses]

export type ListWhatsappLogsData = {
  body?: never
  path?: never
  query?: {
    limit?: number
  }
  url: '/whatsapp/logs'
}

export type ListWhatsappLogsResponses = {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      id: string
      receivedAt: string
      direction: string
      signatureValid?: boolean
      summary: string
      headers?: {
        [key: string]: string
      }
      payload?: unknown
    }>
  }
}

export type ListWhatsappLogsResponse =
  ListWhatsappLogsResponses[keyof ListWhatsappLogsResponses]
