// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {})
}

export type HealthCheckData = {
  body?: never
  path?: never
  query?: never
  url: '/health'
}

export type HealthCheckErrors = {
  /**
   * Default Response
   */
  503: {
    status: string
    db?: string
    redis?: string
  }
}

export type HealthCheckError = HealthCheckErrors[keyof HealthCheckErrors]

export type HealthCheckResponses = {
  /**
   * Default Response
   */
  200: {
    status: string
    db?: string
    redis?: string
  }
}

export type HealthCheckResponse =
  HealthCheckResponses[keyof HealthCheckResponses]

export type LivenessProbeData = {
  body?: never
  path?: never
  query?: never
  url: '/health/live'
}

export type LivenessProbeResponses = {
  /**
   * Default Response
   */
  200: {
    status: string
  }
}

export type LivenessProbeResponse =
  LivenessProbeResponses[keyof LivenessProbeResponses]

export type ReadinessProbeData = {
  body?: never
  path?: never
  query?: never
  url: '/health/ready'
}

export type ReadinessProbeErrors = {
  /**
   * Default Response
   */
  503: {
    status: string
    db?: string
    redis?: string
  }
}

export type ReadinessProbeError =
  ReadinessProbeErrors[keyof ReadinessProbeErrors]

export type ReadinessProbeResponses = {
  /**
   * Default Response
   */
  200: {
    status: string
    db?: string
    redis?: string
  }
}

export type ReadinessProbeResponse =
  ReadinessProbeResponses[keyof ReadinessProbeResponses]

export type ListContactsData = {
  body?: never
  path?: never
  query?: {
    q?: string
    isBlocked?: string
    page?: number
    limit?: number
  }
  url: '/contacts/'
}

export type ListContactsResponses = {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      id: string
      whatsAppAccountId: string
      waId: string
      phoneNumber: string
      name: string | null
      profileName: string | null
      email: string | null
      notes: string | null
      isBlocked: boolean
      createdAt: Date
      updatedAt: Date
      conversationCount: number
      openConversationCount: number
      lastInteractionAt: Date | null
    }>
    meta: {
      total: number
      page: number
      limit: number
      totalPages: number
      hasNext: boolean
    }
  }
}

export type ListContactsResponse =
  ListContactsResponses[keyof ListContactsResponses]

export type GetContactData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/contacts/{id}'
}

export type GetContactResponses = {
  /**
   * Default Response
   */
  200: {
    id: string
    whatsAppAccountId: string
    waId: string
    phoneNumber: string
    name: string | null
    profileName: string | null
    email: string | null
    notes: string | null
    isBlocked: boolean
    createdAt: Date
    updatedAt: Date
    conversationCount: number
    openConversationCount: number
    lastInteractionAt: Date | null
    conversations: Array<{
      id: string
      status: 'OPEN' | 'PENDING' | 'CLOSED'
      priority: 'LOW' | 'MEDIUM' | 'HIGH'
      subject: string | null
      lastMessageAt: Date | null
      assignedTo: {
        id: string
        name: string
        image: string | null
      } | null
    }>
  }
}

export type GetContactResponse = GetContactResponses[keyof GetContactResponses]

export type UpdateContactData = {
  body: {
    name?: string | null
    email?: string | null
    notes?: string | null
  }
  path: {
    id: string
  }
  query?: never
  url: '/contacts/{id}'
}

export type UpdateContactResponses = {
  /**
   * Default Response
   */
  200: {
    id: string
    whatsAppAccountId: string
    waId: string
    phoneNumber: string
    name: string | null
    profileName: string | null
    email: string | null
    notes: string | null
    isBlocked: boolean
    createdAt: Date
    updatedAt: Date
    conversationCount: number
    openConversationCount: number
    lastInteractionAt: Date | null
  }
}

export type UpdateContactResponse =
  UpdateContactResponses[keyof UpdateContactResponses]

export type BlockContactData = {
  body: {
    blocked: boolean
  }
  path: {
    id: string
  }
  query?: never
  url: '/contacts/{id}/block'
}

export type BlockContactResponses = {
  /**
   * Default Response
   */
  200: {
    id: string
    whatsAppAccountId: string
    waId: string
    phoneNumber: string
    name: string | null
    profileName: string | null
    email: string | null
    notes: string | null
    isBlocked: boolean
    createdAt: Date
    updatedAt: Date
    conversationCount: number
    openConversationCount: number
    lastInteractionAt: Date | null
  }
}

export type BlockContactResponse =
  BlockContactResponses[keyof BlockContactResponses]

export type ListConversationsData = {
  body?: never
  path?: never
  query?: {
    status?: 'OPEN' | 'PENDING' | 'CLOSED'
    priority?: 'LOW' | 'MEDIUM' | 'HIGH'
    assignedToId?: string
    teamId?: string
    q?: string
    scope?: 'mine' | 'unassigned' | 'all'
    page?: number
    limit?: number
  }
  url: '/conversations/'
}

export type ListConversationsResponses = {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      id: string
      whatsAppAccountId: string
      contactId: string
      assignedToId: string | null
      teamId: string | null
      status: 'OPEN' | 'PENDING' | 'CLOSED'
      priority: 'LOW' | 'MEDIUM' | 'HIGH'
      channel: 'WHATSAPP'
      subject: string | null
      lastMessageAt: Date | null
      lastMessageText: string | null
      lastInboundAt: Date | null
      unreadCount: number
      assignedAt: Date | null
      closedAt: Date | null
      closedById: string | null
      createdAt: Date
      updatedAt: Date
      contact: {
        id: string
        waId: string
        phoneNumber: string
        name: string | null
        profileName: string | null
        isBlocked: boolean
      }
      assignedTo: {
        id: string
        name: string
        email: string
        image: string | null
      } | null
    }>
    meta: {
      total: number
      page: number
      limit: number
      totalPages: number
      hasNext: boolean
    }
  }
}

export type ListConversationsResponse =
  ListConversationsResponses[keyof ListConversationsResponses]

export type GetConversationData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/conversations/{id}'
}

export type GetConversationResponses = {
  /**
   * Default Response
   */
  200: {
    id: string
    whatsAppAccountId: string
    contactId: string
    assignedToId: string | null
    teamId: string | null
    status: 'OPEN' | 'PENDING' | 'CLOSED'
    priority: 'LOW' | 'MEDIUM' | 'HIGH'
    channel: 'WHATSAPP'
    subject: string | null
    lastMessageAt: Date | null
    lastMessageText: string | null
    lastInboundAt: Date | null
    unreadCount: number
    assignedAt: Date | null
    closedAt: Date | null
    closedById: string | null
    createdAt: Date
    updatedAt: Date
    contact: {
      id: string
      waId: string
      phoneNumber: string
      name: string | null
      profileName: string | null
      isBlocked: boolean
    }
    assignedTo: {
      id: string
      name: string
      email: string
      image: string | null
    } | null
    canSendFreeText: boolean
    windowExpiresAt: Date | null
  }
}

export type GetConversationResponse =
  GetConversationResponses[keyof GetConversationResponses]

export type UpdateConversationData = {
  body: {
    priority: 'LOW' | 'MEDIUM' | 'HIGH'
  }
  path: {
    id: string
  }
  query?: never
  url: '/conversations/{id}'
}

export type UpdateConversationResponses = {
  /**
   * Default Response
   */
  200: {
    id: string
    whatsAppAccountId: string
    contactId: string
    assignedToId: string | null
    teamId: string | null
    status: 'OPEN' | 'PENDING' | 'CLOSED'
    priority: 'LOW' | 'MEDIUM' | 'HIGH'
    channel: 'WHATSAPP'
    subject: string | null
    lastMessageAt: Date | null
    lastMessageText: string | null
    lastInboundAt: Date | null
    unreadCount: number
    assignedAt: Date | null
    closedAt: Date | null
    closedById: string | null
    createdAt: Date
    updatedAt: Date
    contact: {
      id: string
      waId: string
      phoneNumber: string
      name: string | null
      profileName: string | null
      isBlocked: boolean
    }
    assignedTo: {
      id: string
      name: string
      email: string
      image: string | null
    } | null
  }
}

export type UpdateConversationResponse =
  UpdateConversationResponses[keyof UpdateConversationResponses]

export type MarkConversationReadData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/conversations/{id}/read'
}

export type MarkConversationReadResponses = {
  /**
   * Default Response
   */
  200: {
    id: string
    whatsAppAccountId: string
    contactId: string
    assignedToId: string | null
    teamId: string | null
    status: 'OPEN' | 'PENDING' | 'CLOSED'
    priority: 'LOW' | 'MEDIUM' | 'HIGH'
    channel: 'WHATSAPP'
    subject: string | null
    lastMessageAt: Date | null
    lastMessageText: string | null
    lastInboundAt: Date | null
    unreadCount: number
    assignedAt: Date | null
    closedAt: Date | null
    closedById: string | null
    createdAt: Date
    updatedAt: Date
    contact: {
      id: string
      waId: string
      phoneNumber: string
      name: string | null
      profileName: string | null
      isBlocked: boolean
    }
    assignedTo: {
      id: string
      name: string
      email: string
      image: string | null
    } | null
  }
}

export type MarkConversationReadResponse =
  MarkConversationReadResponses[keyof MarkConversationReadResponses]

export type AssignConversationData = {
  body: {
    userId: string
    expectedAssigneeId: string | null
  }
  path: {
    id: string
  }
  query?: never
  url: '/conversations/{id}/assign'
}

export type AssignConversationResponses = {
  /**
   * Default Response
   */
  200: {
    id: string
    whatsAppAccountId: string
    contactId: string
    assignedToId: string | null
    teamId: string | null
    status: 'OPEN' | 'PENDING' | 'CLOSED'
    priority: 'LOW' | 'MEDIUM' | 'HIGH'
    channel: 'WHATSAPP'
    subject: string | null
    lastMessageAt: Date | null
    lastMessageText: string | null
    lastInboundAt: Date | null
    unreadCount: number
    assignedAt: Date | null
    closedAt: Date | null
    closedById: string | null
    createdAt: Date
    updatedAt: Date
    contact: {
      id: string
      waId: string
      phoneNumber: string
      name: string | null
      profileName: string | null
      isBlocked: boolean
    }
    assignedTo: {
      id: string
      name: string
      email: string
      image: string | null
    } | null
  }
}

export type AssignConversationResponse =
  AssignConversationResponses[keyof AssignConversationResponses]

export type UnassignConversationData = {
  body: {
    expectedAssigneeId: string | null
  }
  path: {
    id: string
  }
  query?: never
  url: '/conversations/{id}/unassign'
}

export type UnassignConversationResponses = {
  /**
   * Default Response
   */
  200: {
    id: string
    whatsAppAccountId: string
    contactId: string
    assignedToId: string | null
    teamId: string | null
    status: 'OPEN' | 'PENDING' | 'CLOSED'
    priority: 'LOW' | 'MEDIUM' | 'HIGH'
    channel: 'WHATSAPP'
    subject: string | null
    lastMessageAt: Date | null
    lastMessageText: string | null
    lastInboundAt: Date | null
    unreadCount: number
    assignedAt: Date | null
    closedAt: Date | null
    closedById: string | null
    createdAt: Date
    updatedAt: Date
    contact: {
      id: string
      waId: string
      phoneNumber: string
      name: string | null
      profileName: string | null
      isBlocked: boolean
    }
    assignedTo: {
      id: string
      name: string
      email: string
      image: string | null
    } | null
  }
}

export type UnassignConversationResponse =
  UnassignConversationResponses[keyof UnassignConversationResponses]

export type CloseConversationData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/conversations/{id}/close'
}

export type CloseConversationResponses = {
  /**
   * Default Response
   */
  200: {
    id: string
    whatsAppAccountId: string
    contactId: string
    assignedToId: string | null
    teamId: string | null
    status: 'OPEN' | 'PENDING' | 'CLOSED'
    priority: 'LOW' | 'MEDIUM' | 'HIGH'
    channel: 'WHATSAPP'
    subject: string | null
    lastMessageAt: Date | null
    lastMessageText: string | null
    lastInboundAt: Date | null
    unreadCount: number
    assignedAt: Date | null
    closedAt: Date | null
    closedById: string | null
    createdAt: Date
    updatedAt: Date
    contact: {
      id: string
      waId: string
      phoneNumber: string
      name: string | null
      profileName: string | null
      isBlocked: boolean
    }
    assignedTo: {
      id: string
      name: string
      email: string
      image: string | null
    } | null
  }
}

export type CloseConversationResponse =
  CloseConversationResponses[keyof CloseConversationResponses]

export type ReopenConversationData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/conversations/{id}/reopen'
}

export type ReopenConversationResponses = {
  /**
   * Default Response
   */
  200: {
    id: string
    whatsAppAccountId: string
    contactId: string
    assignedToId: string | null
    teamId: string | null
    status: 'OPEN' | 'PENDING' | 'CLOSED'
    priority: 'LOW' | 'MEDIUM' | 'HIGH'
    channel: 'WHATSAPP'
    subject: string | null
    lastMessageAt: Date | null
    lastMessageText: string | null
    lastInboundAt: Date | null
    unreadCount: number
    assignedAt: Date | null
    closedAt: Date | null
    closedById: string | null
    createdAt: Date
    updatedAt: Date
    contact: {
      id: string
      waId: string
      phoneNumber: string
      name: string | null
      profileName: string | null
      isBlocked: boolean
    }
    assignedTo: {
      id: string
      name: string
      email: string
      image: string | null
    } | null
  }
}

export type ReopenConversationResponse =
  ReopenConversationResponses[keyof ReopenConversationResponses]

export type ListMessagesData = {
  body?: never
  path: {
    id: string
  }
  query?: {
    cursor?: string
    limit?: number
  }
  url: '/conversations/{id}/messages'
}

export type ListMessagesResponses = {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      id: string
      conversationId: string
      senderId: string | null
      direction: 'INBOUND' | 'OUTBOUND'
      type:
        | 'TEXT'
        | 'IMAGE'
        | 'AUDIO'
        | 'VIDEO'
        | 'DOCUMENT'
        | 'STICKER'
        | 'LOCATION'
        | 'CONTACTS'
        | 'TEMPLATE'
        | 'INTERACTIVE'
        | 'REACTION'
        | 'SYSTEM'
        | 'UNSUPPORTED'
      status: 'PENDING' | 'SENT' | 'DELIVERED' | 'READ' | 'FAILED'
      waMessageId: string | null
      waTimestamp: Date | null
      content: string | null
      mediaId: string | null
      mediaUrl: string | null
      mediaMimeType: string | null
      templateName: string | null
      errorCode: string | null
      errorMessage: string | null
      deliveredAt: Date | null
      readAt: Date | null
      failedAt: Date | null
      createdAt: Date
      updatedAt: Date
      sender: {
        id: string
        name: string
        email: string
        image: string | null
      } | null
    }>
    nextCursor: string | null
  }
}

export type ListMessagesResponse =
  ListMessagesResponses[keyof ListMessagesResponses]

export type SendMessageData = {
  body: {
    text: string
  }
  path: {
    id: string
  }
  query?: never
  url: '/conversations/{id}/messages'
}

export type SendMessageResponses = {
  /**
   * Default Response
   */
  200: {
    id: string
    conversationId: string
    senderId: string | null
    direction: 'INBOUND' | 'OUTBOUND'
    type:
      | 'TEXT'
      | 'IMAGE'
      | 'AUDIO'
      | 'VIDEO'
      | 'DOCUMENT'
      | 'STICKER'
      | 'LOCATION'
      | 'CONTACTS'
      | 'TEMPLATE'
      | 'INTERACTIVE'
      | 'REACTION'
      | 'SYSTEM'
      | 'UNSUPPORTED'
    status: 'PENDING' | 'SENT' | 'DELIVERED' | 'READ' | 'FAILED'
    waMessageId: string | null
    waTimestamp: Date | null
    content: string | null
    mediaId: string | null
    mediaUrl: string | null
    mediaMimeType: string | null
    templateName: string | null
    errorCode: string | null
    errorMessage: string | null
    deliveredAt: Date | null
    readAt: Date | null
    failedAt: Date | null
    createdAt: Date
    updatedAt: Date
    sender: {
      id: string
      name: string
      email: string
      image: string | null
    } | null
  }
}

export type SendMessageResponse =
  SendMessageResponses[keyof SendMessageResponses]

export type SendTemplateMessageData = {
  body: {
    templateId: string
    parameters?: {
      header?:
        | Array<string>
        | {
            [key: string]: string
          }
      body?:
        | Array<string>
        | {
            [key: string]: string
          }
      buttons?: Array<
        | Array<string>
        | {
            [key: string]: string
          }
      >
      cards?: Array<
        | Array<string>
        | {
            [key: string]: string
          }
      >
    }
  }
  path: {
    id: string
  }
  query?: never
  url: '/conversations/{id}/messages/template'
}

export type SendTemplateMessageResponses = {
  /**
   * Default Response
   */
  200: {
    id: string
    conversationId: string
    senderId: string | null
    direction: 'INBOUND' | 'OUTBOUND'
    type:
      | 'TEXT'
      | 'IMAGE'
      | 'AUDIO'
      | 'VIDEO'
      | 'DOCUMENT'
      | 'STICKER'
      | 'LOCATION'
      | 'CONTACTS'
      | 'TEMPLATE'
      | 'INTERACTIVE'
      | 'REACTION'
      | 'SYSTEM'
      | 'UNSUPPORTED'
    status: 'PENDING' | 'SENT' | 'DELIVERED' | 'READ' | 'FAILED'
    waMessageId: string | null
    waTimestamp: Date | null
    content: string | null
    mediaId: string | null
    mediaUrl: string | null
    mediaMimeType: string | null
    templateName: string | null
    errorCode: string | null
    errorMessage: string | null
    deliveredAt: Date | null
    readAt: Date | null
    failedAt: Date | null
    createdAt: Date
    updatedAt: Date
    sender: {
      id: string
      name: string
      email: string
      image: string | null
    } | null
  }
}

export type SendTemplateMessageResponse =
  SendTemplateMessageResponses[keyof SendTemplateMessageResponses]

export type StartConversationData = {
  body: {
    phone: string
    templateId: string
    parameters?: {
      header?:
        | Array<string>
        | {
            [key: string]: string
          }
      body?:
        | Array<string>
        | {
            [key: string]: string
          }
      buttons?: Array<
        | Array<string>
        | {
            [key: string]: string
          }
      >
      cards?: Array<
        | Array<string>
        | {
            [key: string]: string
          }
      >
    }
    name?: string
  }
  path?: never
  query?: never
  url: '/conversations/start'
}

export type StartConversationResponses = {
  /**
   * Default Response
   */
  200: {
    conversation: {
      id: string
      whatsAppAccountId: string
      contactId: string
      assignedToId: string | null
      teamId: string | null
      status: 'OPEN' | 'PENDING' | 'CLOSED'
      priority: 'LOW' | 'MEDIUM' | 'HIGH'
      channel: 'WHATSAPP'
      subject: string | null
      lastMessageAt: Date | null
      lastMessageText: string | null
      lastInboundAt: Date | null
      unreadCount: number
      assignedAt: Date | null
      closedAt: Date | null
      closedById: string | null
      createdAt: Date
      updatedAt: Date
      contact: {
        id: string
        waId: string
        phoneNumber: string
        name: string | null
        profileName: string | null
        isBlocked: boolean
      }
      assignedTo: {
        id: string
        name: string
        email: string
        image: string | null
      } | null
    }
    created: boolean
    previousAssignee: {
      id: string
      name: string
      email: string
      image: string | null
    } | null
  }
}

export type StartConversationResponse =
  StartConversationResponses[keyof StartConversationResponses]

export type ListMembersData = {
  body?: never
  path?: never
  query?: never
  url: '/members/'
}

export type ListMembersResponses = {
  /**
   * Default Response
   */
  200: Array<{
    id: string
    name: string | null
    email: string
    image: string | null
    role: string | null
    banned: boolean | null
    createdAt: Date
  }>
}

export type ListMembersResponse =
  ListMembersResponses[keyof ListMembersResponses]

export type ListUsersData = {
  body?: never
  path?: never
  query?: {
    search?: string
    role?: 'admin' | 'manager' | 'agent' | 'viewer' | 'user'
    banned?: boolean
    isStaff?: string
    page?: number
    limit?: number
  }
  url: '/users/'
}

export type ListUsersResponses = {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      id: string
      name: string
      email: string
      image: string | null
      role: string | null
      banned: boolean | null
      emailVerified: boolean
      createdAt: Date
      phone: string | null
    }>
    meta: {
      total: number
      page: number
      limit: number
      totalPages: number
      hasNext: boolean
    }
  }
}

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses]

export type VerifyWhatsappWebhookData = {
  body?: never
  path?: never
  query?: {
    'hub.mode'?: string
    'hub.verify_token'?: string
    'hub.challenge'?: string
  }
  url: '/webhooks/whatsapp'
}

export type VerifyWhatsappWebhookResponses = {
  /**
   * Default Response
   */
  200: string
}

export type VerifyWhatsappWebhookResponse =
  VerifyWhatsappWebhookResponses[keyof VerifyWhatsappWebhookResponses]

export type ReceiveWhatsappWebhookData = {
  body?: never
  path?: never
  query?: never
  url: '/webhooks/whatsapp'
}

export type ReceiveWhatsappWebhookResponses = {
  /**
   * Default Response
   */
  200: {
    received: boolean
  }
}

export type ReceiveWhatsappWebhookResponse =
  ReceiveWhatsappWebhookResponses[keyof ReceiveWhatsappWebhookResponses]

export type DeleteWhatsappConnectionData = {
  body?: never
  path?: never
  query?: never
  url: '/whatsapp/'
}

export type DeleteWhatsappConnectionResponses = {
  /**
   * Default Response
   */
  200: {
    deleted: boolean
  }
}

export type DeleteWhatsappConnectionResponse =
  DeleteWhatsappConnectionResponses[keyof DeleteWhatsappConnectionResponses]

export type GetWhatsappConnectionData = {
  body?: never
  path?: never
  query?: never
  url: '/whatsapp/'
}

export type GetWhatsappConnectionResponses = {
  /**
   * Default Response
   */
  200: {
    configured: boolean
    connection: {
      accessToken: string
      appSecret: string
      phoneNumberId: string
      wabaId: string
      appId: string | null
      verifyToken: string
      webhookBaseUrl: string | null
      displayPhoneNumber: string | null
      verifiedName: string | null
      qualityRating: string | null
      lastCheckedAt: Date | null
    } | null
    webhookUrl: string
    encryptionConfigured: boolean
    webhookBaseIsLocal: boolean
  }
}

export type GetWhatsappConnectionResponse =
  GetWhatsappConnectionResponses[keyof GetWhatsappConnectionResponses]

export type UpdateWhatsappConnectionData = {
  body: {
    accessToken: string
    appSecret: string
    phoneNumberId: string
    wabaId: string
    appId?: string
    verifyToken: string
    webhookBaseUrl?: string
  }
  path?: never
  query?: never
  url: '/whatsapp/'
}

export type UpdateWhatsappConnectionResponses = {
  /**
   * Default Response
   */
  200: {
    configured: boolean
    connection: {
      accessToken: string
      appSecret: string
      phoneNumberId: string
      wabaId: string
      appId: string | null
      verifyToken: string
      webhookBaseUrl: string | null
      displayPhoneNumber: string | null
      verifiedName: string | null
      qualityRating: string | null
      lastCheckedAt: Date | null
    } | null
    webhookUrl: string
    encryptionConfigured: boolean
    webhookBaseIsLocal: boolean
  }
}

export type UpdateWhatsappConnectionResponse =
  UpdateWhatsappConnectionResponses[keyof UpdateWhatsappConnectionResponses]

export type CheckWhatsappHealthData = {
  body?: never
  path?: never
  query?: never
  url: '/whatsapp/health'
}

export type CheckWhatsappHealthResponses = {
  /**
   * Default Response
   */
  200: {
    id: string
    displayPhoneNumber: string | null
    verifiedName: string | null
    qualityRating: string | null
    messagingLimitTier: string | null
    checkedAt: Date
  }
}

export type CheckWhatsappHealthResponse =
  CheckWhatsappHealthResponses[keyof CheckWhatsappHealthResponses]

export type GetWhatsappReadinessData = {
  body?: never
  path?: never
  query?: never
  url: '/whatsapp/readiness'
}

export type GetWhatsappReadinessResponses = {
  /**
   * Default Response
   */
  200: {
    checks: Array<{
      id: string
      label: string
      status: 'ok' | 'pending' | 'error' | 'skipped'
      detail: string
      action: 'register_number' | 'subscribe_app' | 'select_number'
    }>
  }
}

export type GetWhatsappReadinessResponse =
  GetWhatsappReadinessResponses[keyof GetWhatsappReadinessResponses]

export type ListWhatsappPhoneNumbersData = {
  body?: never
  path?: never
  query?: never
  url: '/whatsapp/phone-numbers'
}

export type ListWhatsappPhoneNumbersResponses = {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      id: string
      displayPhoneNumber: string | null
      verifiedName: string | null
      qualityRating: string | null
      platformType: string | null
      codeVerificationStatus: string | null
    }>
  }
}

export type ListWhatsappPhoneNumbersResponse =
  ListWhatsappPhoneNumbersResponses[keyof ListWhatsappPhoneNumbersResponses]

export type RegisterWhatsappNumberData = {
  body: {
    pin: string
  }
  path?: never
  query?: never
  url: '/whatsapp/register-number'
}

export type RegisterWhatsappNumberResponses = {
  /**
   * Default Response
   */
  200: {
    success: boolean
  }
}

export type RegisterWhatsappNumberResponse =
  RegisterWhatsappNumberResponses[keyof RegisterWhatsappNumberResponses]

export type SubscribeWhatsappAppData = {
  body?: never
  path?: never
  query?: never
  url: '/whatsapp/subscribe-app'
}

export type SubscribeWhatsappAppResponses = {
  /**
   * Default Response
   */
  200: {
    success: boolean
  }
}

export type SubscribeWhatsappAppResponse =
  SubscribeWhatsappAppResponses[keyof SubscribeWhatsappAppResponses]

export type SendWhatsappTestMessageData = {
  body: {
    to: string
    kind?: 'text' | 'template'
    text?: string
    templateName?: string
    languageCode?: string
  }
  path?: never
  query?: never
  url: '/whatsapp/test-message'
}

export type SendWhatsappTestMessageResponses = {
  /**
   * Default Response
   */
  200: {
    messageId: string
  }
}

export type SendWhatsappTestMessageResponse =
  SendWhatsappTestMessageResponses[keyof SendWhatsappTestMessageResponses]

export type ListWhatsappLogsData = {
  body?: never
  path?: never
  query?: {
    limit?: number
  }
  url: '/whatsapp/logs'
}

export type ListWhatsappLogsResponses = {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      id: string
      receivedAt: string
      direction: string
      signatureValid?: boolean
      summary: string
      headers?: {
        [key: string]: string
      }
      payload?: unknown
    }>
  }
}

export type ListWhatsappLogsResponse =
  ListWhatsappLogsResponses[keyof ListWhatsappLogsResponses]

export type ListWhatsappTemplatesData = {
  body?: never
  path?: never
  query?: {
    q?: string
    category?: string
    status?: string
    language?: string
    page?: number
    limit?: number
  }
  url: '/whatsapp/templates/'
}

export type ListWhatsappTemplatesResponses = {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      id: string
      name: string
      language: string
      category: string
      metaTemplateId: string | null
      remoteStatus: string | null
      remoteQuality: string | null
      rejectionReason: string | null
      remoteUpdatedAt: Date | null
      lastSyncAttemptAt: Date | null
      lastSyncError: string | null
      createdById: string
      updatedById: string
      createdAt: Date
      updatedAt: Date
      latestRevision: {
        id: string
        version: number
        state: 'DRAFT' | 'SUBMITTED' | 'SUPERSEDED'
        lockVersion: number
        parameterFormat: string
        submittedAt: Date | null
        submittedById: string | null
        createdAt: Date
        updatedAt: Date
      } | null
      draftRevision: {
        id: string
        version: number
        state: 'DRAFT' | 'SUBMITTED' | 'SUPERSEDED'
        lockVersion: number
        parameterFormat: string
        submittedAt: Date | null
        submittedById: string | null
        createdAt: Date
        updatedAt: Date
      } | null
      submittedRevision: {
        id: string
        version: number
        state: 'DRAFT' | 'SUBMITTED' | 'SUPERSEDED'
        lockVersion: number
        parameterFormat: string
        submittedAt: Date | null
        submittedById: string | null
        createdAt: Date
        updatedAt: Date
      } | null
    }>
    meta: {
      total: number
      page: number
      limit: number
      totalPages: number
      hasNext: boolean
    }
  }
}

export type ListWhatsappTemplatesResponse =
  ListWhatsappTemplatesResponses[keyof ListWhatsappTemplatesResponses]

export type CreateWhatsappTemplateDraftData = {
  body: {
    name: string
    definition: {
      category: 'MARKETING' | 'UTILITY' | 'AUTHENTICATION'
      language: string
      parameterFormat: 'POSITIONAL' | 'NAMED'
      components: Array<
        | {
            type: 'HEADER'
            format: 'TEXT'
            text: string
            examples?: Array<string>
          }
        | {
            type: 'HEADER'
            format: 'IMAGE' | 'VIDEO' | 'DOCUMENT'
            assetId?: string
            example?: string
          }
        | {
            type: 'HEADER'
            format: 'LOCATION'
          }
        | {
            type: 'BODY'
            text: string
            examples?: Array<string>
          }
        | {
            type: 'FOOTER'
            text: string
          }
        | {
            type: 'BUTTONS'
            buttons: Array<
              | {
                  kind: 'QUICK_REPLY'
                  text: string
                }
              | {
                  kind: 'URL'
                  text: string
                  url: string
                  examples?: Array<string>
                }
              | {
                  kind: 'PHONE_NUMBER'
                  text: string
                  phoneNumber: string
                }
              | {
                  kind: 'COPY_CODE'
                  text: string
                  example?: string
                }
              | {
                  kind: 'OTP'
                  otpType: 'COPY_CODE' | 'ONE_TAP' | 'ZERO_TAP'
                  text: string
                  autofillText?: string
                  packageName?: string
                  signatureHash?: string
                }
              | {
                  kind: 'CATALOG'
                  text: string
                  thumbnailProductRetailerId?: string
                }
              | {
                  kind: 'FLOW'
                  text: string
                  flowId: string
                  flowAction?: 'navigate' | 'data_exchange'
                  navigateScreen?: string
                  flowData?: {
                    [key: string]: unknown
                  }
                }
            >
          }
        | {
            type: 'CAROUSEL'
            cards: Array<{
              header: {
                format: 'IMAGE' | 'VIDEO' | 'DOCUMENT'
                assetId?: string
                example?: string
              }
              body: {
                text: string
                examples?: Array<string>
              }
              buttons?: Array<
                | {
                    kind: 'QUICK_REPLY'
                    text: string
                  }
                | {
                    kind: 'URL'
                    text: string
                    url: string
                    examples?: Array<string>
                  }
                | {
                    kind: 'PHONE_NUMBER'
                    text: string
                    phoneNumber: string
                  }
                | {
                    kind: 'COPY_CODE'
                    text: string
                    example?: string
                  }
                | {
                    kind: 'OTP'
                    otpType: 'COPY_CODE' | 'ONE_TAP' | 'ZERO_TAP'
                    text: string
                    autofillText?: string
                    packageName?: string
                    signatureHash?: string
                  }
                | {
                    kind: 'CATALOG'
                    text: string
                    thumbnailProductRetailerId?: string
                  }
                | {
                    kind: 'FLOW'
                    text: string
                    flowId: string
                    flowAction?: 'navigate' | 'data_exchange'
                    navigateScreen?: string
                    flowData?: {
                      [key: string]: unknown
                    }
                  }
              >
            }>
          }
        | {
            type: 'LIMITED_TIME_OFFER'
            text: string
            hasExpiration?: boolean
          }
        | {
            type: 'CUSTOM'
            raw: {
              [key: string]: unknown
            }
          }
      >
    }
  }
  path?: never
  query?: never
  url: '/whatsapp/templates/'
}

export type CreateWhatsappTemplateDraftResponses = {
  /**
   * Default Response
   */
  201: {
    id: string
    name: string
    language: string
    category: string
    metaTemplateId: string | null
    remoteStatus: string | null
    remoteQuality: string | null
    rejectionReason: string | null
    remoteUpdatedAt: Date | null
    lastSyncAttemptAt: Date | null
    lastSyncError: string | null
    createdById: string
    updatedById: string
    createdAt: Date
    updatedAt: Date
    latestRevision: {
      id: string
      version: number
      state: 'DRAFT' | 'SUBMITTED' | 'SUPERSEDED'
      lockVersion: number
      parameterFormat: string
      submittedAt: Date | null
      submittedById: string | null
      createdAt: Date
      updatedAt: Date
    } | null
    draftRevision: {
      id: string
      version: number
      state: 'DRAFT' | 'SUBMITTED' | 'SUPERSEDED'
      lockVersion: number
      parameterFormat: string
      submittedAt: Date | null
      submittedById: string | null
      createdAt: Date
      updatedAt: Date
    } | null
    submittedRevision: {
      id: string
      version: number
      state: 'DRAFT' | 'SUBMITTED' | 'SUPERSEDED'
      lockVersion: number
      parameterFormat: string
      submittedAt: Date | null
      submittedById: string | null
      createdAt: Date
      updatedAt: Date
    } | null
    definition: {
      category: 'MARKETING' | 'UTILITY' | 'AUTHENTICATION'
      language: string
      parameterFormat: 'POSITIONAL' | 'NAMED'
      components: Array<
        | {
            type: 'HEADER'
            format: 'TEXT'
            text: string
            examples?: Array<string>
          }
        | {
            type: 'HEADER'
            format: 'IMAGE' | 'VIDEO' | 'DOCUMENT'
            assetId?: string
            example?: string
          }
        | {
            type: 'HEADER'
            format: 'LOCATION'
          }
        | {
            type: 'BODY'
            text: string
            examples?: Array<string>
          }
        | {
            type: 'FOOTER'
            text: string
          }
        | {
            type: 'BUTTONS'
            buttons: Array<
              | {
                  kind: 'QUICK_REPLY'
                  text: string
                }
              | {
                  kind: 'URL'
                  text: string
                  url: string
                  examples?: Array<string>
                }
              | {
                  kind: 'PHONE_NUMBER'
                  text: string
                  phoneNumber: string
                }
              | {
                  kind: 'COPY_CODE'
                  text: string
                  example?: string
                }
              | {
                  kind: 'OTP'
                  otpType: 'COPY_CODE' | 'ONE_TAP' | 'ZERO_TAP'
                  text: string
                  autofillText?: string
                  packageName?: string
                  signatureHash?: string
                }
              | {
                  kind: 'CATALOG'
                  text: string
                  thumbnailProductRetailerId?: string
                }
              | {
                  kind: 'FLOW'
                  text: string
                  flowId: string
                  flowAction?: 'navigate' | 'data_exchange'
                  navigateScreen?: string
                  flowData?: {
                    [key: string]: unknown
                  }
                }
            >
          }
        | {
            type: 'CAROUSEL'
            cards: Array<{
              header: {
                format: 'IMAGE' | 'VIDEO' | 'DOCUMENT'
                assetId?: string
                example?: string
              }
              body: {
                text: string
                examples?: Array<string>
              }
              buttons?: Array<
                | {
                    kind: 'QUICK_REPLY'
                    text: string
                  }
                | {
                    kind: 'URL'
                    text: string
                    url: string
                    examples?: Array<string>
                  }
                | {
                    kind: 'PHONE_NUMBER'
                    text: string
                    phoneNumber: string
                  }
                | {
                    kind: 'COPY_CODE'
                    text: string
                    example?: string
                  }
                | {
                    kind: 'OTP'
                    otpType: 'COPY_CODE' | 'ONE_TAP' | 'ZERO_TAP'
                    text: string
                    autofillText?: string
                    packageName?: string
                    signatureHash?: string
                  }
                | {
                    kind: 'CATALOG'
                    text: string
                    thumbnailProductRetailerId?: string
                  }
                | {
                    kind: 'FLOW'
                    text: string
                    flowId: string
                    flowAction?: 'navigate' | 'data_exchange'
                    navigateScreen?: string
                    flowData?: {
                      [key: string]: unknown
                    }
                  }
              >
            }>
          }
        | {
            type: 'LIMITED_TIME_OFFER'
            text: string
            hasExpiration?: boolean
          }
        | {
            type: 'CUSTOM'
            raw: {
              [key: string]: unknown
            }
          }
      >
    } | null
  }
}

export type CreateWhatsappTemplateDraftResponse =
  CreateWhatsappTemplateDraftResponses[keyof CreateWhatsappTemplateDraftResponses]

export type DeleteWhatsappTemplateDraftData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/whatsapp/templates/{id}'
}

export type DeleteWhatsappTemplateDraftResponses = {
  /**
   * Default Response
   */
  200: {
    removedTemplate: boolean
  }
}

export type DeleteWhatsappTemplateDraftResponse =
  DeleteWhatsappTemplateDraftResponses[keyof DeleteWhatsappTemplateDraftResponses]

export type GetWhatsappTemplateData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/whatsapp/templates/{id}'
}

export type GetWhatsappTemplateResponses = {
  /**
   * Default Response
   */
  200: {
    id: string
    name: string
    language: string
    category: string
    metaTemplateId: string | null
    remoteStatus: string | null
    remoteQuality: string | null
    rejectionReason: string | null
    remoteUpdatedAt: Date | null
    lastSyncAttemptAt: Date | null
    lastSyncError: string | null
    createdById: string
    updatedById: string
    createdAt: Date
    updatedAt: Date
    latestRevision: {
      id: string
      version: number
      state: 'DRAFT' | 'SUBMITTED' | 'SUPERSEDED'
      lockVersion: number
      parameterFormat: string
      submittedAt: Date | null
      submittedById: string | null
      createdAt: Date
      updatedAt: Date
    } | null
    draftRevision: {
      id: string
      version: number
      state: 'DRAFT' | 'SUBMITTED' | 'SUPERSEDED'
      lockVersion: number
      parameterFormat: string
      submittedAt: Date | null
      submittedById: string | null
      createdAt: Date
      updatedAt: Date
    } | null
    submittedRevision: {
      id: string
      version: number
      state: 'DRAFT' | 'SUBMITTED' | 'SUPERSEDED'
      lockVersion: number
      parameterFormat: string
      submittedAt: Date | null
      submittedById: string | null
      createdAt: Date
      updatedAt: Date
    } | null
    definition: {
      category: 'MARKETING' | 'UTILITY' | 'AUTHENTICATION'
      language: string
      parameterFormat: 'POSITIONAL' | 'NAMED'
      components: Array<
        | {
            type: 'HEADER'
            format: 'TEXT'
            text: string
            examples?: Array<string>
          }
        | {
            type: 'HEADER'
            format: 'IMAGE' | 'VIDEO' | 'DOCUMENT'
            assetId?: string
            example?: string
          }
        | {
            type: 'HEADER'
            format: 'LOCATION'
          }
        | {
            type: 'BODY'
            text: string
            examples?: Array<string>
          }
        | {
            type: 'FOOTER'
            text: string
          }
        | {
            type: 'BUTTONS'
            buttons: Array<
              | {
                  kind: 'QUICK_REPLY'
                  text: string
                }
              | {
                  kind: 'URL'
                  text: string
                  url: string
                  examples?: Array<string>
                }
              | {
                  kind: 'PHONE_NUMBER'
                  text: string
                  phoneNumber: string
                }
              | {
                  kind: 'COPY_CODE'
                  text: string
                  example?: string
                }
              | {
                  kind: 'OTP'
                  otpType: 'COPY_CODE' | 'ONE_TAP' | 'ZERO_TAP'
                  text: string
                  autofillText?: string
                  packageName?: string
                  signatureHash?: string
                }
              | {
                  kind: 'CATALOG'
                  text: string
                  thumbnailProductRetailerId?: string
                }
              | {
                  kind: 'FLOW'
                  text: string
                  flowId: string
                  flowAction?: 'navigate' | 'data_exchange'
                  navigateScreen?: string
                  flowData?: {
                    [key: string]: unknown
                  }
                }
            >
          }
        | {
            type: 'CAROUSEL'
            cards: Array<{
              header: {
                format: 'IMAGE' | 'VIDEO' | 'DOCUMENT'
                assetId?: string
                example?: string
              }
              body: {
                text: string
                examples?: Array<string>
              }
              buttons?: Array<
                | {
                    kind: 'QUICK_REPLY'
                    text: string
                  }
                | {
                    kind: 'URL'
                    text: string
                    url: string
                    examples?: Array<string>
                  }
                | {
                    kind: 'PHONE_NUMBER'
                    text: string
                    phoneNumber: string
                  }
                | {
                    kind: 'COPY_CODE'
                    text: string
                    example?: string
                  }
                | {
                    kind: 'OTP'
                    otpType: 'COPY_CODE' | 'ONE_TAP' | 'ZERO_TAP'
                    text: string
                    autofillText?: string
                    packageName?: string
                    signatureHash?: string
                  }
                | {
                    kind: 'CATALOG'
                    text: string
                    thumbnailProductRetailerId?: string
                  }
                | {
                    kind: 'FLOW'
                    text: string
                    flowId: string
                    flowAction?: 'navigate' | 'data_exchange'
                    navigateScreen?: string
                    flowData?: {
                      [key: string]: unknown
                    }
                  }
              >
            }>
          }
        | {
            type: 'LIMITED_TIME_OFFER'
            text: string
            hasExpiration?: boolean
          }
        | {
            type: 'CUSTOM'
            raw: {
              [key: string]: unknown
            }
          }
      >
    } | null
  }
}

export type GetWhatsappTemplateResponse =
  GetWhatsappTemplateResponses[keyof GetWhatsappTemplateResponses]

export type UpdateWhatsappTemplateDraftData = {
  body: {
    expectedLockVersion: number
    definition: {
      category: 'MARKETING' | 'UTILITY' | 'AUTHENTICATION'
      language: string
      parameterFormat: 'POSITIONAL' | 'NAMED'
      components: Array<
        | {
            type: 'HEADER'
            format: 'TEXT'
            text: string
            examples?: Array<string>
          }
        | {
            type: 'HEADER'
            format: 'IMAGE' | 'VIDEO' | 'DOCUMENT'
            assetId?: string
            example?: string
          }
        | {
            type: 'HEADER'
            format: 'LOCATION'
          }
        | {
            type: 'BODY'
            text: string
            examples?: Array<string>
          }
        | {
            type: 'FOOTER'
            text: string
          }
        | {
            type: 'BUTTONS'
            buttons: Array<
              | {
                  kind: 'QUICK_REPLY'
                  text: string
                }
              | {
                  kind: 'URL'
                  text: string
                  url: string
                  examples?: Array<string>
                }
              | {
                  kind: 'PHONE_NUMBER'
                  text: string
                  phoneNumber: string
                }
              | {
                  kind: 'COPY_CODE'
                  text: string
                  example?: string
                }
              | {
                  kind: 'OTP'
                  otpType: 'COPY_CODE' | 'ONE_TAP' | 'ZERO_TAP'
                  text: string
                  autofillText?: string
                  packageName?: string
                  signatureHash?: string
                }
              | {
                  kind: 'CATALOG'
                  text: string
                  thumbnailProductRetailerId?: string
                }
              | {
                  kind: 'FLOW'
                  text: string
                  flowId: string
                  flowAction?: 'navigate' | 'data_exchange'
                  navigateScreen?: string
                  flowData?: {
                    [key: string]: unknown
                  }
                }
            >
          }
        | {
            type: 'CAROUSEL'
            cards: Array<{
              header: {
                format: 'IMAGE' | 'VIDEO' | 'DOCUMENT'
                assetId?: string
                example?: string
              }
              body: {
                text: string
                examples?: Array<string>
              }
              buttons?: Array<
                | {
                    kind: 'QUICK_REPLY'
                    text: string
                  }
                | {
                    kind: 'URL'
                    text: string
                    url: string
                    examples?: Array<string>
                  }
                | {
                    kind: 'PHONE_NUMBER'
                    text: string
                    phoneNumber: string
                  }
                | {
                    kind: 'COPY_CODE'
                    text: string
                    example?: string
                  }
                | {
                    kind: 'OTP'
                    otpType: 'COPY_CODE' | 'ONE_TAP' | 'ZERO_TAP'
                    text: string
                    autofillText?: string
                    packageName?: string
                    signatureHash?: string
                  }
                | {
                    kind: 'CATALOG'
                    text: string
                    thumbnailProductRetailerId?: string
                  }
                | {
                    kind: 'FLOW'
                    text: string
                    flowId: string
                    flowAction?: 'navigate' | 'data_exchange'
                    navigateScreen?: string
                    flowData?: {
                      [key: string]: unknown
                    }
                  }
              >
            }>
          }
        | {
            type: 'LIMITED_TIME_OFFER'
            text: string
            hasExpiration?: boolean
          }
        | {
            type: 'CUSTOM'
            raw: {
              [key: string]: unknown
            }
          }
      >
    }
  }
  path: {
    id: string
  }
  query?: never
  url: '/whatsapp/templates/{id}'
}

export type UpdateWhatsappTemplateDraftResponses = {
  /**
   * Default Response
   */
  200: {
    id: string
    name: string
    language: string
    category: string
    metaTemplateId: string | null
    remoteStatus: string | null
    remoteQuality: string | null
    rejectionReason: string | null
    remoteUpdatedAt: Date | null
    lastSyncAttemptAt: Date | null
    lastSyncError: string | null
    createdById: string
    updatedById: string
    createdAt: Date
    updatedAt: Date
    latestRevision: {
      id: string
      version: number
      state: 'DRAFT' | 'SUBMITTED' | 'SUPERSEDED'
      lockVersion: number
      parameterFormat: string
      submittedAt: Date | null
      submittedById: string | null
      createdAt: Date
      updatedAt: Date
    } | null
    draftRevision: {
      id: string
      version: number
      state: 'DRAFT' | 'SUBMITTED' | 'SUPERSEDED'
      lockVersion: number
      parameterFormat: string
      submittedAt: Date | null
      submittedById: string | null
      createdAt: Date
      updatedAt: Date
    } | null
    submittedRevision: {
      id: string
      version: number
      state: 'DRAFT' | 'SUBMITTED' | 'SUPERSEDED'
      lockVersion: number
      parameterFormat: string
      submittedAt: Date | null
      submittedById: string | null
      createdAt: Date
      updatedAt: Date
    } | null
    definition: {
      category: 'MARKETING' | 'UTILITY' | 'AUTHENTICATION'
      language: string
      parameterFormat: 'POSITIONAL' | 'NAMED'
      components: Array<
        | {
            type: 'HEADER'
            format: 'TEXT'
            text: string
            examples?: Array<string>
          }
        | {
            type: 'HEADER'
            format: 'IMAGE' | 'VIDEO' | 'DOCUMENT'
            assetId?: string
            example?: string
          }
        | {
            type: 'HEADER'
            format: 'LOCATION'
          }
        | {
            type: 'BODY'
            text: string
            examples?: Array<string>
          }
        | {
            type: 'FOOTER'
            text: string
          }
        | {
            type: 'BUTTONS'
            buttons: Array<
              | {
                  kind: 'QUICK_REPLY'
                  text: string
                }
              | {
                  kind: 'URL'
                  text: string
                  url: string
                  examples?: Array<string>
                }
              | {
                  kind: 'PHONE_NUMBER'
                  text: string
                  phoneNumber: string
                }
              | {
                  kind: 'COPY_CODE'
                  text: string
                  example?: string
                }
              | {
                  kind: 'OTP'
                  otpType: 'COPY_CODE' | 'ONE_TAP' | 'ZERO_TAP'
                  text: string
                  autofillText?: string
                  packageName?: string
                  signatureHash?: string
                }
              | {
                  kind: 'CATALOG'
                  text: string
                  thumbnailProductRetailerId?: string
                }
              | {
                  kind: 'FLOW'
                  text: string
                  flowId: string
                  flowAction?: 'navigate' | 'data_exchange'
                  navigateScreen?: string
                  flowData?: {
                    [key: string]: unknown
                  }
                }
            >
          }
        | {
            type: 'CAROUSEL'
            cards: Array<{
              header: {
                format: 'IMAGE' | 'VIDEO' | 'DOCUMENT'
                assetId?: string
                example?: string
              }
              body: {
                text: string
                examples?: Array<string>
              }
              buttons?: Array<
                | {
                    kind: 'QUICK_REPLY'
                    text: string
                  }
                | {
                    kind: 'URL'
                    text: string
                    url: string
                    examples?: Array<string>
                  }
                | {
                    kind: 'PHONE_NUMBER'
                    text: string
                    phoneNumber: string
                  }
                | {
                    kind: 'COPY_CODE'
                    text: string
                    example?: string
                  }
                | {
                    kind: 'OTP'
                    otpType: 'COPY_CODE' | 'ONE_TAP' | 'ZERO_TAP'
                    text: string
                    autofillText?: string
                    packageName?: string
                    signatureHash?: string
                  }
                | {
                    kind: 'CATALOG'
                    text: string
                    thumbnailProductRetailerId?: string
                  }
                | {
                    kind: 'FLOW'
                    text: string
                    flowId: string
                    flowAction?: 'navigate' | 'data_exchange'
                    navigateScreen?: string
                    flowData?: {
                      [key: string]: unknown
                    }
                  }
              >
            }>
          }
        | {
            type: 'LIMITED_TIME_OFFER'
            text: string
            hasExpiration?: boolean
          }
        | {
            type: 'CUSTOM'
            raw: {
              [key: string]: unknown
            }
          }
      >
    } | null
  }
}

export type UpdateWhatsappTemplateDraftResponse =
  UpdateWhatsappTemplateDraftResponses[keyof UpdateWhatsappTemplateDraftResponses]

export type ListWhatsappTemplateRevisionsData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/whatsapp/templates/{id}/revisions'
}

export type ListWhatsappTemplateRevisionsResponses = {
  /**
   * Default Response
   */
  200: {
    data: Array<{
      id: string
      version: number
      state: 'DRAFT' | 'SUBMITTED' | 'SUPERSEDED'
      lockVersion: number
      parameterFormat: string
      submittedAt: Date | null
      submittedById: string | null
      createdAt: Date
      updatedAt: Date
      definition: {
        category: 'MARKETING' | 'UTILITY' | 'AUTHENTICATION'
        language: string
        parameterFormat: 'POSITIONAL' | 'NAMED'
        components: Array<
          | {
              type: 'HEADER'
              format: 'TEXT'
              text: string
              examples?: Array<string>
            }
          | {
              type: 'HEADER'
              format: 'IMAGE' | 'VIDEO' | 'DOCUMENT'
              assetId?: string
              example?: string
            }
          | {
              type: 'HEADER'
              format: 'LOCATION'
            }
          | {
              type: 'BODY'
              text: string
              examples?: Array<string>
            }
          | {
              type: 'FOOTER'
              text: string
            }
          | {
              type: 'BUTTONS'
              buttons: Array<
                | {
                    kind: 'QUICK_REPLY'
                    text: string
                  }
                | {
                    kind: 'URL'
                    text: string
                    url: string
                    examples?: Array<string>
                  }
                | {
                    kind: 'PHONE_NUMBER'
                    text: string
                    phoneNumber: string
                  }
                | {
                    kind: 'COPY_CODE'
                    text: string
                    example?: string
                  }
                | {
                    kind: 'OTP'
                    otpType: 'COPY_CODE' | 'ONE_TAP' | 'ZERO_TAP'
                    text: string
                    autofillText?: string
                    packageName?: string
                    signatureHash?: string
                  }
                | {
                    kind: 'CATALOG'
                    text: string
                    thumbnailProductRetailerId?: string
                  }
                | {
                    kind: 'FLOW'
                    text: string
                    flowId: string
                    flowAction?: 'navigate' | 'data_exchange'
                    navigateScreen?: string
                    flowData?: {
                      [key: string]: unknown
                    }
                  }
              >
            }
          | {
              type: 'CAROUSEL'
              cards: Array<{
                header: {
                  format: 'IMAGE' | 'VIDEO' | 'DOCUMENT'
                  assetId?: string
                  example?: string
                }
                body: {
                  text: string
                  examples?: Array<string>
                }
                buttons?: Array<
                  | {
                      kind: 'QUICK_REPLY'
                      text: string
                    }
                  | {
                      kind: 'URL'
                      text: string
                      url: string
                      examples?: Array<string>
                    }
                  | {
                      kind: 'PHONE_NUMBER'
                      text: string
                      phoneNumber: string
                    }
                  | {
                      kind: 'COPY_CODE'
                      text: string
                      example?: string
                    }
                  | {
                      kind: 'OTP'
                      otpType: 'COPY_CODE' | 'ONE_TAP' | 'ZERO_TAP'
                      text: string
                      autofillText?: string
                      packageName?: string
                      signatureHash?: string
                    }
                  | {
                      kind: 'CATALOG'
                      text: string
                      thumbnailProductRetailerId?: string
                    }
                  | {
                      kind: 'FLOW'
                      text: string
                      flowId: string
                      flowAction?: 'navigate' | 'data_exchange'
                      navigateScreen?: string
                      flowData?: {
                        [key: string]: unknown
                      }
                    }
                >
              }>
            }
          | {
              type: 'LIMITED_TIME_OFFER'
              text: string
              hasExpiration?: boolean
            }
          | {
              type: 'CUSTOM'
              raw: {
                [key: string]: unknown
              }
            }
        >
      } | null
      submission: {
        status: string | null
        code: string | null
        message: string | null
      } | null
    }>
  }
}

export type ListWhatsappTemplateRevisionsResponse =
  ListWhatsappTemplateRevisionsResponses[keyof ListWhatsappTemplateRevisionsResponses]

export type DuplicateWhatsappTemplateData = {
  body: {
    name: string
  }
  path: {
    id: string
  }
  query?: never
  url: '/whatsapp/templates/{id}/duplicate'
}

export type DuplicateWhatsappTemplateResponses = {
  /**
   * Default Response
   */
  201: {
    id: string
    name: string
    language: string
    category: string
    metaTemplateId: string | null
    remoteStatus: string | null
    remoteQuality: string | null
    rejectionReason: string | null
    remoteUpdatedAt: Date | null
    lastSyncAttemptAt: Date | null
    lastSyncError: string | null
    createdById: string
    updatedById: string
    createdAt: Date
    updatedAt: Date
    latestRevision: {
      id: string
      version: number
      state: 'DRAFT' | 'SUBMITTED' | 'SUPERSEDED'
      lockVersion: number
      parameterFormat: string
      submittedAt: Date | null
      submittedById: string | null
      createdAt: Date
      updatedAt: Date
    } | null
    draftRevision: {
      id: string
      version: number
      state: 'DRAFT' | 'SUBMITTED' | 'SUPERSEDED'
      lockVersion: number
      parameterFormat: string
      submittedAt: Date | null
      submittedById: string | null
      createdAt: Date
      updatedAt: Date
    } | null
    submittedRevision: {
      id: string
      version: number
      state: 'DRAFT' | 'SUBMITTED' | 'SUPERSEDED'
      lockVersion: number
      parameterFormat: string
      submittedAt: Date | null
      submittedById: string | null
      createdAt: Date
      updatedAt: Date
    } | null
    definition: {
      category: 'MARKETING' | 'UTILITY' | 'AUTHENTICATION'
      language: string
      parameterFormat: 'POSITIONAL' | 'NAMED'
      components: Array<
        | {
            type: 'HEADER'
            format: 'TEXT'
            text: string
            examples?: Array<string>
          }
        | {
            type: 'HEADER'
            format: 'IMAGE' | 'VIDEO' | 'DOCUMENT'
            assetId?: string
            example?: string
          }
        | {
            type: 'HEADER'
            format: 'LOCATION'
          }
        | {
            type: 'BODY'
            text: string
            examples?: Array<string>
          }
        | {
            type: 'FOOTER'
            text: string
          }
        | {
            type: 'BUTTONS'
            buttons: Array<
              | {
                  kind: 'QUICK_REPLY'
                  text: string
                }
              | {
                  kind: 'URL'
                  text: string
                  url: string
                  examples?: Array<string>
                }
              | {
                  kind: 'PHONE_NUMBER'
                  text: string
                  phoneNumber: string
                }
              | {
                  kind: 'COPY_CODE'
                  text: string
                  example?: string
                }
              | {
                  kind: 'OTP'
                  otpType: 'COPY_CODE' | 'ONE_TAP' | 'ZERO_TAP'
                  text: string
                  autofillText?: string
                  packageName?: string
                  signatureHash?: string
                }
              | {
                  kind: 'CATALOG'
                  text: string
                  thumbnailProductRetailerId?: string
                }
              | {
                  kind: 'FLOW'
                  text: string
                  flowId: string
                  flowAction?: 'navigate' | 'data_exchange'
                  navigateScreen?: string
                  flowData?: {
                    [key: string]: unknown
                  }
                }
            >
          }
        | {
            type: 'CAROUSEL'
            cards: Array<{
              header: {
                format: 'IMAGE' | 'VIDEO' | 'DOCUMENT'
                assetId?: string
                example?: string
              }
              body: {
                text: string
                examples?: Array<string>
              }
              buttons?: Array<
                | {
                    kind: 'QUICK_REPLY'
                    text: string
                  }
                | {
                    kind: 'URL'
                    text: string
                    url: string
                    examples?: Array<string>
                  }
                | {
                    kind: 'PHONE_NUMBER'
                    text: string
                    phoneNumber: string
                  }
                | {
                    kind: 'COPY_CODE'
                    text: string
                    example?: string
                  }
                | {
                    kind: 'OTP'
                    otpType: 'COPY_CODE' | 'ONE_TAP' | 'ZERO_TAP'
                    text: string
                    autofillText?: string
                    packageName?: string
                    signatureHash?: string
                  }
                | {
                    kind: 'CATALOG'
                    text: string
                    thumbnailProductRetailerId?: string
                  }
                | {
                    kind: 'FLOW'
                    text: string
                    flowId: string
                    flowAction?: 'navigate' | 'data_exchange'
                    navigateScreen?: string
                    flowData?: {
                      [key: string]: unknown
                    }
                  }
              >
            }>
          }
        | {
            type: 'LIMITED_TIME_OFFER'
            text: string
            hasExpiration?: boolean
          }
        | {
            type: 'CUSTOM'
            raw: {
              [key: string]: unknown
            }
          }
      >
    } | null
  }
}

export type DuplicateWhatsappTemplateResponse =
  DuplicateWhatsappTemplateResponses[keyof DuplicateWhatsappTemplateResponses]

export type ValidateWhatsappTemplateRevisionData = {
  body: {
    definition: unknown
  }
  path?: never
  query?: never
  url: '/whatsapp/templates/validate'
}

export type ValidateWhatsappTemplateRevisionResponses = {
  /**
   * Default Response
   */
  200: {
    valid: boolean
    issues: Array<{
      path: string
      message: string
    }>
  }
}

export type ValidateWhatsappTemplateRevisionResponse =
  ValidateWhatsappTemplateRevisionResponses[keyof ValidateWhatsappTemplateRevisionResponses]

export type SubmitWhatsappTemplateData = {
  body: {
    idempotencyKey?: string
  }
  path: {
    id: string
  }
  query?: never
  url: '/whatsapp/templates/{id}/submit'
}

export type SubmitWhatsappTemplateResponses = {
  /**
   * Default Response
   */
  200: {
    template: {
      id: string
      name: string
      language: string
      category: string
      metaTemplateId: string | null
      remoteStatus: string | null
      remoteQuality: string | null
      rejectionReason: string | null
      remoteUpdatedAt: Date | null
      lastSyncAttemptAt: Date | null
      lastSyncError: string | null
      createdById: string
      updatedById: string
      createdAt: Date
      updatedAt: Date
      latestRevision: {
        id: string
        version: number
        state: 'DRAFT' | 'SUBMITTED' | 'SUPERSEDED'
        lockVersion: number
        parameterFormat: string
        submittedAt: Date | null
        submittedById: string | null
        createdAt: Date
        updatedAt: Date
      } | null
      draftRevision: {
        id: string
        version: number
        state: 'DRAFT' | 'SUBMITTED' | 'SUPERSEDED'
        lockVersion: number
        parameterFormat: string
        submittedAt: Date | null
        submittedById: string | null
        createdAt: Date
        updatedAt: Date
      } | null
      submittedRevision: {
        id: string
        version: number
        state: 'DRAFT' | 'SUBMITTED' | 'SUPERSEDED'
        lockVersion: number
        parameterFormat: string
        submittedAt: Date | null
        submittedById: string | null
        createdAt: Date
        updatedAt: Date
      } | null
      definition: {
        category: 'MARKETING' | 'UTILITY' | 'AUTHENTICATION'
        language: string
        parameterFormat: 'POSITIONAL' | 'NAMED'
        components: Array<
          | {
              type: 'HEADER'
              format: 'TEXT'
              text: string
              examples?: Array<string>
            }
          | {
              type: 'HEADER'
              format: 'IMAGE' | 'VIDEO' | 'DOCUMENT'
              assetId?: string
              example?: string
            }
          | {
              type: 'HEADER'
              format: 'LOCATION'
            }
          | {
              type: 'BODY'
              text: string
              examples?: Array<string>
            }
          | {
              type: 'FOOTER'
              text: string
            }
          | {
              type: 'BUTTONS'
              buttons: Array<
                | {
                    kind: 'QUICK_REPLY'
                    text: string
                  }
                | {
                    kind: 'URL'
                    text: string
                    url: string
                    examples?: Array<string>
                  }
                | {
                    kind: 'PHONE_NUMBER'
                    text: string
                    phoneNumber: string
                  }
                | {
                    kind: 'COPY_CODE'
                    text: string
                    example?: string
                  }
                | {
                    kind: 'OTP'
                    otpType: 'COPY_CODE' | 'ONE_TAP' | 'ZERO_TAP'
                    text: string
                    autofillText?: string
                    packageName?: string
                    signatureHash?: string
                  }
                | {
                    kind: 'CATALOG'
                    text: string
                    thumbnailProductRetailerId?: string
                  }
                | {
                    kind: 'FLOW'
                    text: string
                    flowId: string
                    flowAction?: 'navigate' | 'data_exchange'
                    navigateScreen?: string
                    flowData?: {
                      [key: string]: unknown
                    }
                  }
              >
            }
          | {
              type: 'CAROUSEL'
              cards: Array<{
                header: {
                  format: 'IMAGE' | 'VIDEO' | 'DOCUMENT'
                  assetId?: string
                  example?: string
                }
                body: {
                  text: string
                  examples?: Array<string>
                }
                buttons?: Array<
                  | {
                      kind: 'QUICK_REPLY'
                      text: string
                    }
                  | {
                      kind: 'URL'
                      text: string
                      url: string
                      examples?: Array<string>
                    }
                  | {
                      kind: 'PHONE_NUMBER'
                      text: string
                      phoneNumber: string
                    }
                  | {
                      kind: 'COPY_CODE'
                      text: string
                      example?: string
                    }
                  | {
                      kind: 'OTP'
                      otpType: 'COPY_CODE' | 'ONE_TAP' | 'ZERO_TAP'
                      text: string
                      autofillText?: string
                      packageName?: string
                      signatureHash?: string
                    }
                  | {
                      kind: 'CATALOG'
                      text: string
                      thumbnailProductRetailerId?: string
                    }
                  | {
                      kind: 'FLOW'
                      text: string
                      flowId: string
                      flowAction?: 'navigate' | 'data_exchange'
                      navigateScreen?: string
                      flowData?: {
                        [key: string]: unknown
                      }
                    }
                >
              }>
            }
          | {
              type: 'LIMITED_TIME_OFFER'
              text: string
              hasExpiration?: boolean
            }
          | {
              type: 'CUSTOM'
              raw: {
                [key: string]: unknown
              }
            }
        >
      } | null
    }
    revisionId: string
    replayed: boolean
  }
}

export type SubmitWhatsappTemplateResponse =
  SubmitWhatsappTemplateResponses[keyof SubmitWhatsappTemplateResponses]

export type SyncWhatsappTemplatesData = {
  body?: never
  path?: never
  query?: never
  url: '/whatsapp/templates/sync'
}

export type SyncWhatsappTemplatesResponses = {
  /**
   * Default Response
   */
  200: {
    imported: number
    updated: number
    failed: number
    nextCursor: null
  }
}

export type SyncWhatsappTemplatesResponse =
  SyncWhatsappTemplatesResponses[keyof SyncWhatsappTemplatesResponses]

export type DeleteWhatsappTemplateRemoteData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/whatsapp/templates/{id}/remote'
}

export type DeleteWhatsappTemplateRemoteResponses = {
  /**
   * Default Response
   */
  200: {
    id: string
    name: string
    language: string
    category: string
    metaTemplateId: string | null
    remoteStatus: string | null
    remoteQuality: string | null
    rejectionReason: string | null
    remoteUpdatedAt: Date | null
    lastSyncAttemptAt: Date | null
    lastSyncError: string | null
    createdById: string
    updatedById: string
    createdAt: Date
    updatedAt: Date
    latestRevision: {
      id: string
      version: number
      state: 'DRAFT' | 'SUBMITTED' | 'SUPERSEDED'
      lockVersion: number
      parameterFormat: string
      submittedAt: Date | null
      submittedById: string | null
      createdAt: Date
      updatedAt: Date
    } | null
    draftRevision: {
      id: string
      version: number
      state: 'DRAFT' | 'SUBMITTED' | 'SUPERSEDED'
      lockVersion: number
      parameterFormat: string
      submittedAt: Date | null
      submittedById: string | null
      createdAt: Date
      updatedAt: Date
    } | null
    submittedRevision: {
      id: string
      version: number
      state: 'DRAFT' | 'SUBMITTED' | 'SUPERSEDED'
      lockVersion: number
      parameterFormat: string
      submittedAt: Date | null
      submittedById: string | null
      createdAt: Date
      updatedAt: Date
    } | null
    definition: {
      category: 'MARKETING' | 'UTILITY' | 'AUTHENTICATION'
      language: string
      parameterFormat: 'POSITIONAL' | 'NAMED'
      components: Array<
        | {
            type: 'HEADER'
            format: 'TEXT'
            text: string
            examples?: Array<string>
          }
        | {
            type: 'HEADER'
            format: 'IMAGE' | 'VIDEO' | 'DOCUMENT'
            assetId?: string
            example?: string
          }
        | {
            type: 'HEADER'
            format: 'LOCATION'
          }
        | {
            type: 'BODY'
            text: string
            examples?: Array<string>
          }
        | {
            type: 'FOOTER'
            text: string
          }
        | {
            type: 'BUTTONS'
            buttons: Array<
              | {
                  kind: 'QUICK_REPLY'
                  text: string
                }
              | {
                  kind: 'URL'
                  text: string
                  url: string
                  examples?: Array<string>
                }
              | {
                  kind: 'PHONE_NUMBER'
                  text: string
                  phoneNumber: string
                }
              | {
                  kind: 'COPY_CODE'
                  text: string
                  example?: string
                }
              | {
                  kind: 'OTP'
                  otpType: 'COPY_CODE' | 'ONE_TAP' | 'ZERO_TAP'
                  text: string
                  autofillText?: string
                  packageName?: string
                  signatureHash?: string
                }
              | {
                  kind: 'CATALOG'
                  text: string
                  thumbnailProductRetailerId?: string
                }
              | {
                  kind: 'FLOW'
                  text: string
                  flowId: string
                  flowAction?: 'navigate' | 'data_exchange'
                  navigateScreen?: string
                  flowData?: {
                    [key: string]: unknown
                  }
                }
            >
          }
        | {
            type: 'CAROUSEL'
            cards: Array<{
              header: {
                format: 'IMAGE' | 'VIDEO' | 'DOCUMENT'
                assetId?: string
                example?: string
              }
              body: {
                text: string
                examples?: Array<string>
              }
              buttons?: Array<
                | {
                    kind: 'QUICK_REPLY'
                    text: string
                  }
                | {
                    kind: 'URL'
                    text: string
                    url: string
                    examples?: Array<string>
                  }
                | {
                    kind: 'PHONE_NUMBER'
                    text: string
                    phoneNumber: string
                  }
                | {
                    kind: 'COPY_CODE'
                    text: string
                    example?: string
                  }
                | {
                    kind: 'OTP'
                    otpType: 'COPY_CODE' | 'ONE_TAP' | 'ZERO_TAP'
                    text: string
                    autofillText?: string
                    packageName?: string
                    signatureHash?: string
                  }
                | {
                    kind: 'CATALOG'
                    text: string
                    thumbnailProductRetailerId?: string
                  }
                | {
                    kind: 'FLOW'
                    text: string
                    flowId: string
                    flowAction?: 'navigate' | 'data_exchange'
                    navigateScreen?: string
                    flowData?: {
                      [key: string]: unknown
                    }
                  }
              >
            }>
          }
        | {
            type: 'LIMITED_TIME_OFFER'
            text: string
            hasExpiration?: boolean
          }
        | {
            type: 'CUSTOM'
            raw: {
              [key: string]: unknown
            }
          }
      >
    } | null
  }
}

export type DeleteWhatsappTemplateRemoteResponse =
  DeleteWhatsappTemplateRemoteResponses[keyof DeleteWhatsappTemplateRemoteResponses]

export type PrepareWhatsappTemplateAssetUploadData = {
  body: {
    revisionId: string
    fileName: string
    mimeType: string
    byteSize: number
  }
  path?: never
  query?: never
  url: '/whatsapp/templates/assets/prepare'
}

export type PrepareWhatsappTemplateAssetUploadResponses = {
  /**
   * Default Response
   */
  200: {
    assetId: string
    kind: string
    uploadUrl: string
    expiresIn: number
  }
}

export type PrepareWhatsappTemplateAssetUploadResponse =
  PrepareWhatsappTemplateAssetUploadResponses[keyof PrepareWhatsappTemplateAssetUploadResponses]

export type ConfirmWhatsappTemplateAssetUploadData = {
  body?: never
  path: {
    assetId: string
  }
  query?: never
  url: '/whatsapp/templates/assets/{assetId}/confirm'
}

export type ConfirmWhatsappTemplateAssetUploadResponses = {
  /**
   * Default Response
   */
  200: {
    assetId: string
    kind: string
    mimeType: string
    byteSize: number
    metaHandle: string
    reusedMetaHandle: boolean
  }
}

export type ConfirmWhatsappTemplateAssetUploadResponse =
  ConfirmWhatsappTemplateAssetUploadResponses[keyof ConfirmWhatsappTemplateAssetUploadResponses]

export type GetWhatsappTemplateAssetPreviewData = {
  body?: never
  path: {
    assetId: string
  }
  query?: never
  url: '/whatsapp/templates/assets/{assetId}/preview'
}

export type GetWhatsappTemplateAssetPreviewResponses = {
  /**
   * Default Response
   */
  200: {
    url: string
    expiresIn: number
  }
}

export type GetWhatsappTemplateAssetPreviewResponse =
  GetWhatsappTemplateAssetPreviewResponses[keyof GetWhatsappTemplateAssetPreviewResponses]
