// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod'

/**
 * Default Response
 */
export const zHealthCheckResponse = z.object({
  status: z.string(),
  db: z.string().optional(),
  redis: z.string().optional(),
})

/**
 * Default Response
 */
export const zLivenessProbeResponse = z.object({
  status: z.string(),
})

/**
 * Default Response
 */
export const zReadinessProbeResponse = z.object({
  status: z.string(),
  db: z.string().optional(),
  redis: z.string().optional(),
})

/**
 * Default Response
 */
export const zListMembersResponse = z.array(
  z.object({
    id: z.string(),
    name: z.string().nullable(),
    email: z
      .email()
      .regex(
        /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/,
      ),
    image: z.string().nullable(),
    role: z.string().nullable(),
    createdAt: z.iso.datetime(),
  }),
)

export const zListUsersQuery = z.object({
  search: z.string().optional(),
  role: z.enum(['admin', 'user']).optional(),
  banned: z.boolean().optional(),
  isStaff: z.string().optional(),
  page: z.int().gte(1).lte(9007199254740991).optional().default(1),
  limit: z.int().gte(1).lte(100).optional().default(20),
})

/**
 * Default Response
 */
export const zListUsersResponse = z.object({
  data: z.array(
    z.object({
      id: z.string(),
      name: z.string(),
      email: z
        .email()
        .regex(
          /^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/,
        ),
      image: z.string().nullable(),
      role: z.string().nullable(),
      banned: z.boolean().nullable(),
      emailVerified: z.boolean(),
      createdAt: z.iso.datetime(),
      phone: z.string().nullable(),
    }),
  ),
  meta: z.object({
    total: z.number(),
    page: z.number(),
    limit: z.number(),
    totalPages: z.number(),
    hasNext: z.boolean(),
  }),
})

export const zVerifyWhatsappWebhookQuery = z.object({
  'hub.mode': z.string().optional(),
  'hub.verify_token': z.string().optional(),
  'hub.challenge': z.string().optional(),
})

/**
 * Default Response
 */
export const zVerifyWhatsappWebhookResponse = z.string()

/**
 * Default Response
 */
export const zReceiveWhatsappWebhookResponse = z.object({
  received: z.boolean(),
})

/**
 * Default Response
 */
export const zDeleteWhatsappConnectionResponse = z.object({
  deleted: z.boolean(),
})

/**
 * Default Response
 */
export const zGetWhatsappConnectionResponse = z.object({
  configured: z.boolean(),
  connection: z
    .object({
      accessToken: z.string(),
      appSecret: z.string(),
      phoneNumberId: z.string(),
      wabaId: z.string(),
      verifyToken: z.string(),
      webhookBaseUrl: z.string().nullable(),
      displayPhoneNumber: z.string().nullable(),
      verifiedName: z.string().nullable(),
      qualityRating: z.string().nullable(),
      lastCheckedAt: z.iso.datetime().nullable(),
    })
    .nullable(),
  webhookUrl: z.string(),
  encryptionConfigured: z.boolean(),
  webhookBaseIsLocal: z.boolean(),
})

export const zUpdateWhatsappConnectionBody = z.object({
  accessToken: z.string().min(1),
  appSecret: z.string().min(1),
  phoneNumberId: z.string().min(1),
  wabaId: z.string().min(1),
  verifyToken: z.string().min(1),
  webhookBaseUrl: z.string().optional(),
})

/**
 * Default Response
 */
export const zUpdateWhatsappConnectionResponse = z.object({
  configured: z.boolean(),
  connection: z
    .object({
      accessToken: z.string(),
      appSecret: z.string(),
      phoneNumberId: z.string(),
      wabaId: z.string(),
      verifyToken: z.string(),
      webhookBaseUrl: z.string().nullable(),
      displayPhoneNumber: z.string().nullable(),
      verifiedName: z.string().nullable(),
      qualityRating: z.string().nullable(),
      lastCheckedAt: z.iso.datetime().nullable(),
    })
    .nullable(),
  webhookUrl: z.string(),
  encryptionConfigured: z.boolean(),
  webhookBaseIsLocal: z.boolean(),
})

/**
 * Default Response
 */
export const zCheckWhatsappHealthResponse = z.object({
  id: z.string(),
  displayPhoneNumber: z.string().nullable(),
  verifiedName: z.string().nullable(),
  qualityRating: z.string().nullable(),
  messagingLimitTier: z.string().nullable(),
  checkedAt: z.iso.datetime(),
})

export const zSendWhatsappTestMessageBody = z.object({
  to: z.string().min(1),
  text: z.string().min(1),
})

/**
 * Default Response
 */
export const zSendWhatsappTestMessageResponse = z.object({
  messageId: z.string(),
})

export const zListWhatsappLogsQuery = z.object({
  limit: z.int().gte(1).lte(200).optional().default(200),
})

/**
 * Default Response
 */
export const zListWhatsappLogsResponse = z.object({
  data: z.array(
    z.object({
      id: z.string(),
      receivedAt: z.string(),
      direction: z.string(),
      signatureValid: z.boolean().optional(),
      summary: z.string(),
      headers: z.record(z.string(), z.string()).optional(),
      payload: z.unknown().optional(),
    }),
  ),
})
