// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from '@tanstack/react-query'

import { client } from '../client.gen'
import {
  checkWhatsappHealth,
  deleteWhatsappConnection,
  getWhatsappConnection,
  healthCheck,
  listMembers,
  listUsers,
  listWhatsappLogs,
  livenessProbe,
  type Options,
  readinessProbe,
  receiveWhatsappWebhook,
  sendWhatsappTestMessage,
  updateWhatsappConnection,
  verifyWhatsappWebhook,
} from '../sdk.gen'
import type {
  CheckWhatsappHealthData,
  CheckWhatsappHealthResponse,
  DeleteWhatsappConnectionData,
  DeleteWhatsappConnectionResponse,
  GetWhatsappConnectionData,
  GetWhatsappConnectionResponse,
  HealthCheckData,
  HealthCheckError,
  HealthCheckResponse,
  ListMembersData,
  ListMembersResponse,
  ListUsersData,
  ListUsersResponse,
  ListWhatsappLogsData,
  ListWhatsappLogsResponse,
  LivenessProbeData,
  LivenessProbeResponse,
  ReadinessProbeData,
  ReadinessProbeError,
  ReadinessProbeResponse,
  ReceiveWhatsappWebhookData,
  ReceiveWhatsappWebhookResponse,
  SendWhatsappTestMessageData,
  SendWhatsappTestMessageResponse,
  UpdateWhatsappConnectionData,
  UpdateWhatsappConnectionResponse,
  VerifyWhatsappWebhookData,
  VerifyWhatsappWebhookResponse,
} from '../types.gen'

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const healthCheckQueryKey = (options?: Options<HealthCheckData>) =>
  createQueryKey('healthCheck', options, false, ['Health'])

/**
 * Health check
 */
export const healthCheckOptions = (options?: Options<HealthCheckData>) =>
  queryOptions<
    HealthCheckResponse,
    HealthCheckError,
    HealthCheckResponse,
    ReturnType<typeof healthCheckQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthCheck({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: healthCheckQueryKey(options),
  })

export const livenessProbeQueryKey = (options?: Options<LivenessProbeData>) =>
  createQueryKey('livenessProbe', options, false, ['Health'])

/**
 * Liveness probe (process alive)
 */
export const livenessProbeOptions = (options?: Options<LivenessProbeData>) =>
  queryOptions<
    LivenessProbeResponse,
    DefaultError,
    LivenessProbeResponse,
    ReturnType<typeof livenessProbeQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await livenessProbe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: livenessProbeQueryKey(options),
  })

export const readinessProbeQueryKey = (options?: Options<ReadinessProbeData>) =>
  createQueryKey('readinessProbe', options, false, ['Health'])

/**
 * Readiness probe (dependencies healthy)
 */
export const readinessProbeOptions = (options?: Options<ReadinessProbeData>) =>
  queryOptions<
    ReadinessProbeResponse,
    ReadinessProbeError,
    ReadinessProbeResponse,
    ReturnType<typeof readinessProbeQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await readinessProbe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: readinessProbeQueryKey(options),
  })

export const listMembersQueryKey = (options?: Options<ListMembersData>) =>
  createQueryKey('listMembers', options, false, ['Members'])

/**
 * List users
 */
export const listMembersOptions = (options?: Options<ListMembersData>) =>
  queryOptions<
    ListMembersResponse,
    DefaultError,
    ListMembersResponse,
    ReturnType<typeof listMembersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listMembers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listMembersQueryKey(options),
  })

export const listUsersQueryKey = (options?: Options<ListUsersData>) =>
  createQueryKey('listUsers', options, false, ['Users'])

/**
 * List users
 */
export const listUsersOptions = (options?: Options<ListUsersData>) =>
  queryOptions<
    ListUsersResponse,
    DefaultError,
    ListUsersResponse,
    ReturnType<typeof listUsersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listUsersQueryKey(options),
  })

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] }
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    }
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    }
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    }
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    }
  }
  return params as unknown as typeof page
}

export const listUsersInfiniteQueryKey = (
  options?: Options<ListUsersData>,
): QueryKey<Options<ListUsersData>> =>
  createQueryKey('listUsers', options, true)

/**
 * List users
 */
export const listUsersInfiniteOptions = (options?: Options<ListUsersData>) => {
  const opts = infiniteQueryOptions<
    ListUsersResponse,
    DefaultError,
    InfiniteData<ListUsersResponse>,
    QueryKey<Options<ListUsersData>>,
    | number
    | Pick<
        QueryKey<Options<ListUsersData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListUsersData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await listUsers({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: listUsersInfiniteQueryKey(options),
    },
  )
  return opts as Omit<typeof opts, 'initialData'>
}

export const verifyWhatsappWebhookQueryKey = (
  options?: Options<VerifyWhatsappWebhookData>,
) => createQueryKey('verifyWhatsappWebhook', options, false, ['Webhooks'])

/**
 * Handshake de verificação do webhook do WhatsApp
 */
export const verifyWhatsappWebhookOptions = (
  options?: Options<VerifyWhatsappWebhookData>,
) =>
  queryOptions<
    VerifyWhatsappWebhookResponse,
    DefaultError,
    VerifyWhatsappWebhookResponse,
    ReturnType<typeof verifyWhatsappWebhookQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await verifyWhatsappWebhook({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: verifyWhatsappWebhookQueryKey(options),
  })

/**
 * Ingestão de eventos do webhook do WhatsApp
 */
export const receiveWhatsappWebhookMutation = (
  options?: Partial<Options<ReceiveWhatsappWebhookData>>,
): UseMutationOptions<
  ReceiveWhatsappWebhookResponse,
  DefaultError,
  Options<ReceiveWhatsappWebhookData>
> => {
  const mutationOptions: UseMutationOptions<
    ReceiveWhatsappWebhookResponse,
    DefaultError,
    Options<ReceiveWhatsappWebhookData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await receiveWhatsappWebhook({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Remove a conexão WhatsApp
 */
export const deleteWhatsappConnectionMutation = (
  options?: Partial<Options<DeleteWhatsappConnectionData>>,
): UseMutationOptions<
  DeleteWhatsappConnectionResponse,
  DefaultError,
  Options<DeleteWhatsappConnectionData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteWhatsappConnectionResponse,
    DefaultError,
    Options<DeleteWhatsappConnectionData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await deleteWhatsappConnection({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getWhatsappConnectionQueryKey = (
  options?: Options<GetWhatsappConnectionData>,
) => createQueryKey('getWhatsappConnection', options, false, ['WhatsApp'])

/**
 * Estado da conexão WhatsApp (segredos mascarados)
 */
export const getWhatsappConnectionOptions = (
  options?: Options<GetWhatsappConnectionData>,
) =>
  queryOptions<
    GetWhatsappConnectionResponse,
    DefaultError,
    GetWhatsappConnectionResponse,
    ReturnType<typeof getWhatsappConnectionQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWhatsappConnection({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getWhatsappConnectionQueryKey(options),
  })

/**
 * Salva as credenciais (valida na Graph API antes de gravar)
 */
export const updateWhatsappConnectionMutation = (
  options?: Partial<Options<UpdateWhatsappConnectionData>>,
): UseMutationOptions<
  UpdateWhatsappConnectionResponse,
  DefaultError,
  Options<UpdateWhatsappConnectionData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateWhatsappConnectionResponse,
    DefaultError,
    Options<UpdateWhatsappConnectionData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await updateWhatsappConnection({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const checkWhatsappHealthQueryKey = (
  options?: Options<CheckWhatsappHealthData>,
) => createQueryKey('checkWhatsappHealth', options, false, ['WhatsApp'])

/**
 * Consulta o número na Graph API (nome, qualidade e tier)
 */
export const checkWhatsappHealthOptions = (
  options?: Options<CheckWhatsappHealthData>,
) =>
  queryOptions<
    CheckWhatsappHealthResponse,
    DefaultError,
    CheckWhatsappHealthResponse,
    ReturnType<typeof checkWhatsappHealthQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await checkWhatsappHealth({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: checkWhatsappHealthQueryKey(options),
  })

/**
 * Envia uma mensagem de teste (texto livre ou template)
 */
export const sendWhatsappTestMessageMutation = (
  options?: Partial<Options<SendWhatsappTestMessageData>>,
): UseMutationOptions<
  SendWhatsappTestMessageResponse,
  DefaultError,
  Options<SendWhatsappTestMessageData>
> => {
  const mutationOptions: UseMutationOptions<
    SendWhatsappTestMessageResponse,
    DefaultError,
    Options<SendWhatsappTestMessageData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await sendWhatsappTestMessage({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listWhatsappLogsQueryKey = (
  options?: Options<ListWhatsappLogsData>,
) => createQueryKey('listWhatsappLogs', options, false, ['WhatsApp'])

/**
 * Histórico do console de webhooks (seed do stream)
 */
export const listWhatsappLogsOptions = (
  options?: Options<ListWhatsappLogsData>,
) =>
  queryOptions<
    ListWhatsappLogsResponse,
    DefaultError,
    ListWhatsappLogsResponse,
    ReturnType<typeof listWhatsappLogsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listWhatsappLogs({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listWhatsappLogsQueryKey(options),
  })
