// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from '@tanstack/react-query'

import { client } from '../client.gen'
import {
  assignConversation,
  blockContact,
  checkWhatsappHealth,
  closeConversation,
  confirmWhatsappTemplateAssetUpload,
  createWhatsappTemplateDraft,
  deleteWhatsappConnection,
  deleteWhatsappTemplateDraft,
  deleteWhatsappTemplateRemote,
  duplicateWhatsappTemplate,
  getContact,
  getConversation,
  getWhatsappConnection,
  getWhatsappReadiness,
  getWhatsappTemplate,
  getWhatsappTemplateAssetPreview,
  healthCheck,
  listContacts,
  listConversations,
  listMembers,
  listMessages,
  listUsers,
  listWhatsappLogs,
  listWhatsappPhoneNumbers,
  listWhatsappTemplateRevisions,
  listWhatsappTemplates,
  livenessProbe,
  markConversationRead,
  type Options,
  prepareWhatsappTemplateAssetUpload,
  readinessProbe,
  receiveWhatsappWebhook,
  registerWhatsappNumber,
  reopenConversation,
  sendMessage,
  sendTemplateMessage,
  sendWhatsappTestMessage,
  startConversation,
  submitWhatsappTemplate,
  subscribeWhatsappApp,
  syncWhatsappTemplates,
  unassignConversation,
  updateContact,
  updateConversation,
  updateWhatsappConnection,
  updateWhatsappTemplateDraft,
  validateWhatsappTemplateRevision,
  verifyWhatsappWebhook,
} from '../sdk.gen'
import type {
  AssignConversationData,
  AssignConversationResponse,
  BlockContactData,
  BlockContactResponse,
  CheckWhatsappHealthData,
  CheckWhatsappHealthResponse,
  CloseConversationData,
  CloseConversationResponse,
  ConfirmWhatsappTemplateAssetUploadData,
  ConfirmWhatsappTemplateAssetUploadResponse,
  CreateWhatsappTemplateDraftData,
  CreateWhatsappTemplateDraftResponse,
  DeleteWhatsappConnectionData,
  DeleteWhatsappConnectionResponse,
  DeleteWhatsappTemplateDraftData,
  DeleteWhatsappTemplateDraftResponse,
  DeleteWhatsappTemplateRemoteData,
  DeleteWhatsappTemplateRemoteResponse,
  DuplicateWhatsappTemplateData,
  DuplicateWhatsappTemplateResponse,
  GetContactData,
  GetContactResponse,
  GetConversationData,
  GetConversationResponse,
  GetWhatsappConnectionData,
  GetWhatsappConnectionResponse,
  GetWhatsappReadinessData,
  GetWhatsappReadinessResponse,
  GetWhatsappTemplateAssetPreviewData,
  GetWhatsappTemplateAssetPreviewResponse,
  GetWhatsappTemplateData,
  GetWhatsappTemplateResponse,
  HealthCheckData,
  HealthCheckError,
  HealthCheckResponse,
  ListContactsData,
  ListContactsResponse,
  ListConversationsData,
  ListConversationsResponse,
  ListMembersData,
  ListMembersResponse,
  ListMessagesData,
  ListMessagesResponse,
  ListUsersData,
  ListUsersResponse,
  ListWhatsappLogsData,
  ListWhatsappLogsResponse,
  ListWhatsappPhoneNumbersData,
  ListWhatsappPhoneNumbersResponse,
  ListWhatsappTemplateRevisionsData,
  ListWhatsappTemplateRevisionsResponse,
  ListWhatsappTemplatesData,
  ListWhatsappTemplatesResponse,
  LivenessProbeData,
  LivenessProbeResponse,
  MarkConversationReadData,
  MarkConversationReadResponse,
  PrepareWhatsappTemplateAssetUploadData,
  PrepareWhatsappTemplateAssetUploadResponse,
  ReadinessProbeData,
  ReadinessProbeError,
  ReadinessProbeResponse,
  ReceiveWhatsappWebhookData,
  ReceiveWhatsappWebhookResponse,
  RegisterWhatsappNumberData,
  RegisterWhatsappNumberResponse,
  ReopenConversationData,
  ReopenConversationResponse,
  SendMessageData,
  SendMessageResponse,
  SendTemplateMessageData,
  SendTemplateMessageResponse,
  SendWhatsappTestMessageData,
  SendWhatsappTestMessageResponse,
  StartConversationData,
  StartConversationResponse,
  SubmitWhatsappTemplateData,
  SubmitWhatsappTemplateResponse,
  SubscribeWhatsappAppData,
  SubscribeWhatsappAppResponse,
  SyncWhatsappTemplatesData,
  SyncWhatsappTemplatesResponse,
  UnassignConversationData,
  UnassignConversationResponse,
  UpdateContactData,
  UpdateContactResponse,
  UpdateConversationData,
  UpdateConversationResponse,
  UpdateWhatsappConnectionData,
  UpdateWhatsappConnectionResponse,
  UpdateWhatsappTemplateDraftData,
  UpdateWhatsappTemplateDraftResponse,
  ValidateWhatsappTemplateRevisionData,
  ValidateWhatsappTemplateRevisionResponse,
  VerifyWhatsappWebhookData,
  VerifyWhatsappWebhookResponse,
} from '../types.gen'

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const healthCheckQueryKey = (options?: Options<HealthCheckData>) =>
  createQueryKey('healthCheck', options, false, ['Health'])

/**
 * Health check
 */
export const healthCheckOptions = (options?: Options<HealthCheckData>) =>
  queryOptions<
    HealthCheckResponse,
    HealthCheckError,
    HealthCheckResponse,
    ReturnType<typeof healthCheckQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthCheck({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: healthCheckQueryKey(options),
  })

export const livenessProbeQueryKey = (options?: Options<LivenessProbeData>) =>
  createQueryKey('livenessProbe', options, false, ['Health'])

/**
 * Liveness probe (process alive)
 */
export const livenessProbeOptions = (options?: Options<LivenessProbeData>) =>
  queryOptions<
    LivenessProbeResponse,
    DefaultError,
    LivenessProbeResponse,
    ReturnType<typeof livenessProbeQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await livenessProbe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: livenessProbeQueryKey(options),
  })

export const readinessProbeQueryKey = (options?: Options<ReadinessProbeData>) =>
  createQueryKey('readinessProbe', options, false, ['Health'])

/**
 * Readiness probe (dependencies healthy)
 */
export const readinessProbeOptions = (options?: Options<ReadinessProbeData>) =>
  queryOptions<
    ReadinessProbeResponse,
    ReadinessProbeError,
    ReadinessProbeResponse,
    ReturnType<typeof readinessProbeQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await readinessProbe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: readinessProbeQueryKey(options),
  })

export const listContactsQueryKey = (options?: Options<ListContactsData>) =>
  createQueryKey('listContacts', options, false, ['Contacts'])

/**
 * Lista contatos visíveis para o solicitante
 */
export const listContactsOptions = (options?: Options<ListContactsData>) =>
  queryOptions<
    ListContactsResponse,
    DefaultError,
    ListContactsResponse,
    ReturnType<typeof listContactsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listContacts({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listContactsQueryKey(options),
  })

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] }
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    }
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    }
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    }
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    }
  }
  return params as unknown as typeof page
}

export const listContactsInfiniteQueryKey = (
  options?: Options<ListContactsData>,
): QueryKey<Options<ListContactsData>> =>
  createQueryKey('listContacts', options, true)

/**
 * Lista contatos visíveis para o solicitante
 */
export const listContactsInfiniteOptions = (
  options?: Options<ListContactsData>,
) => {
  const opts = infiniteQueryOptions<
    ListContactsResponse,
    DefaultError,
    InfiniteData<ListContactsResponse>,
    QueryKey<Options<ListContactsData>>,
    | number
    | Pick<
        QueryKey<Options<ListContactsData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListContactsData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await listContacts({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: listContactsInfiniteQueryKey(options),
    },
  )
  return opts as Omit<typeof opts, 'initialData'>
}

export const getContactQueryKey = (options: Options<GetContactData>) =>
  createQueryKey('getContact', options, false, ['Contacts'])

/**
 * Detalha um contato com as conversas recentes dele
 */
export const getContactOptions = (options: Options<GetContactData>) =>
  queryOptions<
    GetContactResponse,
    DefaultError,
    GetContactResponse,
    ReturnType<typeof getContactQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getContact({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getContactQueryKey(options),
  })

/**
 * Atualiza os dados editáveis do contato
 */
export const updateContactMutation = (
  options?: Partial<Options<UpdateContactData>>,
): UseMutationOptions<
  UpdateContactResponse,
  DefaultError,
  Options<UpdateContactData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateContactResponse,
    DefaultError,
    Options<UpdateContactData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await updateContact({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Bloqueia ou desbloqueia o contato
 */
export const blockContactMutation = (
  options?: Partial<Options<BlockContactData>>,
): UseMutationOptions<
  BlockContactResponse,
  DefaultError,
  Options<BlockContactData>
> => {
  const mutationOptions: UseMutationOptions<
    BlockContactResponse,
    DefaultError,
    Options<BlockContactData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await blockContact({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listConversationsQueryKey = (
  options?: Options<ListConversationsData>,
) => createQueryKey('listConversations', options, false, ['Conversations'])

/**
 * Lista conversas visíveis para o solicitante
 */
export const listConversationsOptions = (
  options?: Options<ListConversationsData>,
) =>
  queryOptions<
    ListConversationsResponse,
    DefaultError,
    ListConversationsResponse,
    ReturnType<typeof listConversationsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listConversations({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listConversationsQueryKey(options),
  })

export const listConversationsInfiniteQueryKey = (
  options?: Options<ListConversationsData>,
): QueryKey<Options<ListConversationsData>> =>
  createQueryKey('listConversations', options, true)

/**
 * Lista conversas visíveis para o solicitante
 */
export const listConversationsInfiniteOptions = (
  options?: Options<ListConversationsData>,
) => {
  const opts = infiniteQueryOptions<
    ListConversationsResponse,
    DefaultError,
    InfiniteData<ListConversationsResponse>,
    QueryKey<Options<ListConversationsData>>,
    | number
    | Pick<
        QueryKey<Options<ListConversationsData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListConversationsData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await listConversations({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: listConversationsInfiniteQueryKey(options),
    },
  )
  return opts as Omit<typeof opts, 'initialData'>
}

export const getConversationQueryKey = (
  options: Options<GetConversationData>,
) => createQueryKey('getConversation', options, false, ['Conversations'])

/**
 * Detalha uma conversa com a janela de 24h calculada
 */
export const getConversationOptions = (options: Options<GetConversationData>) =>
  queryOptions<
    GetConversationResponse,
    DefaultError,
    GetConversationResponse,
    ReturnType<typeof getConversationQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getConversation({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getConversationQueryKey(options),
  })

/**
 * Altera a prioridade da conversa
 */
export const updateConversationMutation = (
  options?: Partial<Options<UpdateConversationData>>,
): UseMutationOptions<
  UpdateConversationResponse,
  DefaultError,
  Options<UpdateConversationData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateConversationResponse,
    DefaultError,
    Options<UpdateConversationData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await updateConversation({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Zera o contador de mensagens não lidas da conversa
 */
export const markConversationReadMutation = (
  options?: Partial<Options<MarkConversationReadData>>,
): UseMutationOptions<
  MarkConversationReadResponse,
  DefaultError,
  Options<MarkConversationReadData>
> => {
  const mutationOptions: UseMutationOptions<
    MarkConversationReadResponse,
    DefaultError,
    Options<MarkConversationReadData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await markConversationRead({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Atribui a conversa a um atendente
 */
export const assignConversationMutation = (
  options?: Partial<Options<AssignConversationData>>,
): UseMutationOptions<
  AssignConversationResponse,
  DefaultError,
  Options<AssignConversationData>
> => {
  const mutationOptions: UseMutationOptions<
    AssignConversationResponse,
    DefaultError,
    Options<AssignConversationData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await assignConversation({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Remove o responsável da conversa
 */
export const unassignConversationMutation = (
  options?: Partial<Options<UnassignConversationData>>,
): UseMutationOptions<
  UnassignConversationResponse,
  DefaultError,
  Options<UnassignConversationData>
> => {
  const mutationOptions: UseMutationOptions<
    UnassignConversationResponse,
    DefaultError,
    Options<UnassignConversationData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await unassignConversation({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Encerra uma conversa
 */
export const closeConversationMutation = (
  options?: Partial<Options<CloseConversationData>>,
): UseMutationOptions<
  CloseConversationResponse,
  DefaultError,
  Options<CloseConversationData>
> => {
  const mutationOptions: UseMutationOptions<
    CloseConversationResponse,
    DefaultError,
    Options<CloseConversationData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await closeConversation({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Reabre uma conversa encerrada
 */
export const reopenConversationMutation = (
  options?: Partial<Options<ReopenConversationData>>,
): UseMutationOptions<
  ReopenConversationResponse,
  DefaultError,
  Options<ReopenConversationData>
> => {
  const mutationOptions: UseMutationOptions<
    ReopenConversationResponse,
    DefaultError,
    Options<ReopenConversationData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await reopenConversation({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listMessagesQueryKey = (options: Options<ListMessagesData>) =>
  createQueryKey('listMessages', options, false, ['Messages'])

/**
 * Lista as mensagens de uma conversa (paginação por cursor)
 */
export const listMessagesOptions = (options: Options<ListMessagesData>) =>
  queryOptions<
    ListMessagesResponse,
    DefaultError,
    ListMessagesResponse,
    ReturnType<typeof listMessagesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listMessages({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listMessagesQueryKey(options),
  })

export const listMessagesInfiniteQueryKey = (
  options: Options<ListMessagesData>,
): QueryKey<Options<ListMessagesData>> =>
  createQueryKey('listMessages', options, true)

/**
 * Lista as mensagens de uma conversa (paginação por cursor)
 */
export const listMessagesInfiniteOptions = (
  options: Options<ListMessagesData>,
) => {
  const opts = infiniteQueryOptions<
    ListMessagesResponse,
    DefaultError,
    InfiniteData<ListMessagesResponse>,
    QueryKey<Options<ListMessagesData>>,
    | string
    | Pick<
        QueryKey<Options<ListMessagesData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListMessagesData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await listMessages({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: listMessagesInfiniteQueryKey(options),
    },
  )
  return opts as Omit<typeof opts, 'initialData'>
}

/**
 * Envia uma mensagem de texto na conversa
 */
export const sendMessageMutation = (
  options?: Partial<Options<SendMessageData>>,
): UseMutationOptions<
  SendMessageResponse,
  DefaultError,
  Options<SendMessageData>
> => {
  const mutationOptions: UseMutationOptions<
    SendMessageResponse,
    DefaultError,
    Options<SendMessageData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await sendMessage({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Envia uma mensagem de modelo (válida fora da janela de 24h)
 */
export const sendTemplateMessageMutation = (
  options?: Partial<Options<SendTemplateMessageData>>,
): UseMutationOptions<
  SendTemplateMessageResponse,
  DefaultError,
  Options<SendTemplateMessageData>
> => {
  const mutationOptions: UseMutationOptions<
    SendTemplateMessageResponse,
    DefaultError,
    Options<SendTemplateMessageData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await sendTemplateMessage({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Inicia uma conversa com um número novo via modelo (template)
 */
export const startConversationMutation = (
  options?: Partial<Options<StartConversationData>>,
): UseMutationOptions<
  StartConversationResponse,
  DefaultError,
  Options<StartConversationData>
> => {
  const mutationOptions: UseMutationOptions<
    StartConversationResponse,
    DefaultError,
    Options<StartConversationData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await startConversation({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listMembersQueryKey = (options?: Options<ListMembersData>) =>
  createQueryKey('listMembers', options, false, ['Members'])

/**
 * List users
 */
export const listMembersOptions = (options?: Options<ListMembersData>) =>
  queryOptions<
    ListMembersResponse,
    DefaultError,
    ListMembersResponse,
    ReturnType<typeof listMembersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listMembers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listMembersQueryKey(options),
  })

export const listUsersQueryKey = (options?: Options<ListUsersData>) =>
  createQueryKey('listUsers', options, false, ['Users'])

/**
 * List users
 */
export const listUsersOptions = (options?: Options<ListUsersData>) =>
  queryOptions<
    ListUsersResponse,
    DefaultError,
    ListUsersResponse,
    ReturnType<typeof listUsersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listUsersQueryKey(options),
  })

export const listUsersInfiniteQueryKey = (
  options?: Options<ListUsersData>,
): QueryKey<Options<ListUsersData>> =>
  createQueryKey('listUsers', options, true)

/**
 * List users
 */
export const listUsersInfiniteOptions = (options?: Options<ListUsersData>) => {
  const opts = infiniteQueryOptions<
    ListUsersResponse,
    DefaultError,
    InfiniteData<ListUsersResponse>,
    QueryKey<Options<ListUsersData>>,
    | number
    | Pick<
        QueryKey<Options<ListUsersData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListUsersData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await listUsers({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: listUsersInfiniteQueryKey(options),
    },
  )
  return opts as Omit<typeof opts, 'initialData'>
}

export const verifyWhatsappWebhookQueryKey = (
  options?: Options<VerifyWhatsappWebhookData>,
) => createQueryKey('verifyWhatsappWebhook', options, false, ['Webhooks'])

/**
 * Handshake de verificação do webhook do WhatsApp
 */
export const verifyWhatsappWebhookOptions = (
  options?: Options<VerifyWhatsappWebhookData>,
) =>
  queryOptions<
    VerifyWhatsappWebhookResponse,
    DefaultError,
    VerifyWhatsappWebhookResponse,
    ReturnType<typeof verifyWhatsappWebhookQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await verifyWhatsappWebhook({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: verifyWhatsappWebhookQueryKey(options),
  })

/**
 * Ingestão de eventos do webhook do WhatsApp
 */
export const receiveWhatsappWebhookMutation = (
  options?: Partial<Options<ReceiveWhatsappWebhookData>>,
): UseMutationOptions<
  ReceiveWhatsappWebhookResponse,
  DefaultError,
  Options<ReceiveWhatsappWebhookData>
> => {
  const mutationOptions: UseMutationOptions<
    ReceiveWhatsappWebhookResponse,
    DefaultError,
    Options<ReceiveWhatsappWebhookData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await receiveWhatsappWebhook({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Remove a conexão WhatsApp
 */
export const deleteWhatsappConnectionMutation = (
  options?: Partial<Options<DeleteWhatsappConnectionData>>,
): UseMutationOptions<
  DeleteWhatsappConnectionResponse,
  DefaultError,
  Options<DeleteWhatsappConnectionData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteWhatsappConnectionResponse,
    DefaultError,
    Options<DeleteWhatsappConnectionData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await deleteWhatsappConnection({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getWhatsappConnectionQueryKey = (
  options?: Options<GetWhatsappConnectionData>,
) => createQueryKey('getWhatsappConnection', options, false, ['WhatsApp'])

/**
 * Estado da conexão WhatsApp (segredos mascarados)
 */
export const getWhatsappConnectionOptions = (
  options?: Options<GetWhatsappConnectionData>,
) =>
  queryOptions<
    GetWhatsappConnectionResponse,
    DefaultError,
    GetWhatsappConnectionResponse,
    ReturnType<typeof getWhatsappConnectionQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWhatsappConnection({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getWhatsappConnectionQueryKey(options),
  })

/**
 * Salva as credenciais (valida na Graph API antes de gravar)
 */
export const updateWhatsappConnectionMutation = (
  options?: Partial<Options<UpdateWhatsappConnectionData>>,
): UseMutationOptions<
  UpdateWhatsappConnectionResponse,
  DefaultError,
  Options<UpdateWhatsappConnectionData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateWhatsappConnectionResponse,
    DefaultError,
    Options<UpdateWhatsappConnectionData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await updateWhatsappConnection({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const checkWhatsappHealthQueryKey = (
  options?: Options<CheckWhatsappHealthData>,
) => createQueryKey('checkWhatsappHealth', options, false, ['WhatsApp'])

/**
 * Consulta o número na Graph API (nome, qualidade e tier)
 */
export const checkWhatsappHealthOptions = (
  options?: Options<CheckWhatsappHealthData>,
) =>
  queryOptions<
    CheckWhatsappHealthResponse,
    DefaultError,
    CheckWhatsappHealthResponse,
    ReturnType<typeof checkWhatsappHealthQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await checkWhatsappHealth({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: checkWhatsappHealthQueryKey(options),
  })

export const getWhatsappReadinessQueryKey = (
  options?: Options<GetWhatsappReadinessData>,
) => createQueryKey('getWhatsappReadiness', options, false, ['WhatsApp'])

/**
 * Diagnóstico completo do setup (roda todas as verificações)
 */
export const getWhatsappReadinessOptions = (
  options?: Options<GetWhatsappReadinessData>,
) =>
  queryOptions<
    GetWhatsappReadinessResponse,
    DefaultError,
    GetWhatsappReadinessResponse,
    ReturnType<typeof getWhatsappReadinessQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWhatsappReadiness({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getWhatsappReadinessQueryKey(options),
  })

export const listWhatsappPhoneNumbersQueryKey = (
  options?: Options<ListWhatsappPhoneNumbersData>,
) => createQueryKey('listWhatsappPhoneNumbers', options, false, ['WhatsApp'])

/**
 * Lista os números do WABA na Cloud API
 */
export const listWhatsappPhoneNumbersOptions = (
  options?: Options<ListWhatsappPhoneNumbersData>,
) =>
  queryOptions<
    ListWhatsappPhoneNumbersResponse,
    DefaultError,
    ListWhatsappPhoneNumbersResponse,
    ReturnType<typeof listWhatsappPhoneNumbersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listWhatsappPhoneNumbers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listWhatsappPhoneNumbersQueryKey(options),
  })

/**
 * Registra o número na Cloud API com o PIN de verificação
 */
export const registerWhatsappNumberMutation = (
  options?: Partial<Options<RegisterWhatsappNumberData>>,
): UseMutationOptions<
  RegisterWhatsappNumberResponse,
  DefaultError,
  Options<RegisterWhatsappNumberData>
> => {
  const mutationOptions: UseMutationOptions<
    RegisterWhatsappNumberResponse,
    DefaultError,
    Options<RegisterWhatsappNumberData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await registerWhatsappNumber({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Inscreve o app no WABA para receber os webhooks
 */
export const subscribeWhatsappAppMutation = (
  options?: Partial<Options<SubscribeWhatsappAppData>>,
): UseMutationOptions<
  SubscribeWhatsappAppResponse,
  DefaultError,
  Options<SubscribeWhatsappAppData>
> => {
  const mutationOptions: UseMutationOptions<
    SubscribeWhatsappAppResponse,
    DefaultError,
    Options<SubscribeWhatsappAppData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await subscribeWhatsappApp({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Envia uma mensagem de teste (texto livre ou template)
 */
export const sendWhatsappTestMessageMutation = (
  options?: Partial<Options<SendWhatsappTestMessageData>>,
): UseMutationOptions<
  SendWhatsappTestMessageResponse,
  DefaultError,
  Options<SendWhatsappTestMessageData>
> => {
  const mutationOptions: UseMutationOptions<
    SendWhatsappTestMessageResponse,
    DefaultError,
    Options<SendWhatsappTestMessageData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await sendWhatsappTestMessage({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listWhatsappLogsQueryKey = (
  options?: Options<ListWhatsappLogsData>,
) => createQueryKey('listWhatsappLogs', options, false, ['WhatsApp'])

/**
 * Histórico do console de webhooks (seed do stream)
 */
export const listWhatsappLogsOptions = (
  options?: Options<ListWhatsappLogsData>,
) =>
  queryOptions<
    ListWhatsappLogsResponse,
    DefaultError,
    ListWhatsappLogsResponse,
    ReturnType<typeof listWhatsappLogsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listWhatsappLogs({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listWhatsappLogsQueryKey(options),
  })

export const listWhatsappTemplatesQueryKey = (
  options?: Options<ListWhatsappTemplatesData>,
) =>
  createQueryKey('listWhatsappTemplates', options, false, ['WhatsAppTemplates'])

/**
 * Lista os modelos da conta ativa com filtros e paginação
 */
export const listWhatsappTemplatesOptions = (
  options?: Options<ListWhatsappTemplatesData>,
) =>
  queryOptions<
    ListWhatsappTemplatesResponse,
    DefaultError,
    ListWhatsappTemplatesResponse,
    ReturnType<typeof listWhatsappTemplatesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listWhatsappTemplates({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listWhatsappTemplatesQueryKey(options),
  })

export const listWhatsappTemplatesInfiniteQueryKey = (
  options?: Options<ListWhatsappTemplatesData>,
): QueryKey<Options<ListWhatsappTemplatesData>> =>
  createQueryKey('listWhatsappTemplates', options, true)

/**
 * Lista os modelos da conta ativa com filtros e paginação
 */
export const listWhatsappTemplatesInfiniteOptions = (
  options?: Options<ListWhatsappTemplatesData>,
) => {
  const opts = infiniteQueryOptions<
    ListWhatsappTemplatesResponse,
    DefaultError,
    InfiniteData<ListWhatsappTemplatesResponse>,
    QueryKey<Options<ListWhatsappTemplatesData>>,
    | number
    | Pick<
        QueryKey<Options<ListWhatsappTemplatesData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListWhatsappTemplatesData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await listWhatsappTemplates({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: listWhatsappTemplatesInfiniteQueryKey(options),
    },
  )
  return opts as Omit<typeof opts, 'initialData'>
}

/**
 * Cria um modelo com a primeira revisão em rascunho
 */
export const createWhatsappTemplateDraftMutation = (
  options?: Partial<Options<CreateWhatsappTemplateDraftData>>,
): UseMutationOptions<
  CreateWhatsappTemplateDraftResponse,
  DefaultError,
  Options<CreateWhatsappTemplateDraftData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateWhatsappTemplateDraftResponse,
    DefaultError,
    Options<CreateWhatsappTemplateDraftData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await createWhatsappTemplateDraft({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Apaga o rascunho (e o modelo, quando nunca foi enviado)
 */
export const deleteWhatsappTemplateDraftMutation = (
  options?: Partial<Options<DeleteWhatsappTemplateDraftData>>,
): UseMutationOptions<
  DeleteWhatsappTemplateDraftResponse,
  DefaultError,
  Options<DeleteWhatsappTemplateDraftData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteWhatsappTemplateDraftResponse,
    DefaultError,
    Options<DeleteWhatsappTemplateDraftData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await deleteWhatsappTemplateDraft({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getWhatsappTemplateQueryKey = (
  options: Options<GetWhatsappTemplateData>,
) =>
  createQueryKey('getWhatsappTemplate', options, false, ['WhatsAppTemplates'])

/**
 * Detalha um modelo com a definição mais recente
 */
export const getWhatsappTemplateOptions = (
  options: Options<GetWhatsappTemplateData>,
) =>
  queryOptions<
    GetWhatsappTemplateResponse,
    DefaultError,
    GetWhatsappTemplateResponse,
    ReturnType<typeof getWhatsappTemplateQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWhatsappTemplate({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getWhatsappTemplateQueryKey(options),
  })

/**
 * Edita o rascunho com trava otimista de versão
 */
export const updateWhatsappTemplateDraftMutation = (
  options?: Partial<Options<UpdateWhatsappTemplateDraftData>>,
): UseMutationOptions<
  UpdateWhatsappTemplateDraftResponse,
  DefaultError,
  Options<UpdateWhatsappTemplateDraftData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateWhatsappTemplateDraftResponse,
    DefaultError,
    Options<UpdateWhatsappTemplateDraftData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await updateWhatsappTemplateDraft({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listWhatsappTemplateRevisionsQueryKey = (
  options: Options<ListWhatsappTemplateRevisionsData>,
) =>
  createQueryKey('listWhatsappTemplateRevisions', options, false, [
    'WhatsAppTemplates',
  ])

/**
 * Histórico de revisões do modelo, da mais nova para a antiga
 */
export const listWhatsappTemplateRevisionsOptions = (
  options: Options<ListWhatsappTemplateRevisionsData>,
) =>
  queryOptions<
    ListWhatsappTemplateRevisionsResponse,
    DefaultError,
    ListWhatsappTemplateRevisionsResponse,
    ReturnType<typeof listWhatsappTemplateRevisionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listWhatsappTemplateRevisions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listWhatsappTemplateRevisionsQueryKey(options),
  })

/**
 * Duplica o modelo em um novo rascunho com outro nome
 */
export const duplicateWhatsappTemplateMutation = (
  options?: Partial<Options<DuplicateWhatsappTemplateData>>,
): UseMutationOptions<
  DuplicateWhatsappTemplateResponse,
  DefaultError,
  Options<DuplicateWhatsappTemplateData>
> => {
  const mutationOptions: UseMutationOptions<
    DuplicateWhatsappTemplateResponse,
    DefaultError,
    Options<DuplicateWhatsappTemplateData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await duplicateWhatsappTemplate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Valida uma definição sem gravar nada
 */
export const validateWhatsappTemplateRevisionMutation = (
  options?: Partial<Options<ValidateWhatsappTemplateRevisionData>>,
): UseMutationOptions<
  ValidateWhatsappTemplateRevisionResponse,
  DefaultError,
  Options<ValidateWhatsappTemplateRevisionData>
> => {
  const mutationOptions: UseMutationOptions<
    ValidateWhatsappTemplateRevisionResponse,
    DefaultError,
    Options<ValidateWhatsappTemplateRevisionData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await validateWhatsappTemplateRevision({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Envia o rascunho para aprovação da Meta
 */
export const submitWhatsappTemplateMutation = (
  options?: Partial<Options<SubmitWhatsappTemplateData>>,
): UseMutationOptions<
  SubmitWhatsappTemplateResponse,
  DefaultError,
  Options<SubmitWhatsappTemplateData>
> => {
  const mutationOptions: UseMutationOptions<
    SubmitWhatsappTemplateResponse,
    DefaultError,
    Options<SubmitWhatsappTemplateData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await submitWhatsappTemplate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Espelha o catálogo da Meta sem tocar nos rascunhos locais
 */
export const syncWhatsappTemplatesMutation = (
  options?: Partial<Options<SyncWhatsappTemplatesData>>,
): UseMutationOptions<
  SyncWhatsappTemplatesResponse,
  DefaultError,
  Options<SyncWhatsappTemplatesData>
> => {
  const mutationOptions: UseMutationOptions<
    SyncWhatsappTemplatesResponse,
    DefaultError,
    Options<SyncWhatsappTemplatesData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await syncWhatsappTemplates({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Apaga o modelo na Meta e zera o espelho remoto local
 */
export const deleteWhatsappTemplateRemoteMutation = (
  options?: Partial<Options<DeleteWhatsappTemplateRemoteData>>,
): UseMutationOptions<
  DeleteWhatsappTemplateRemoteResponse,
  DefaultError,
  Options<DeleteWhatsappTemplateRemoteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteWhatsappTemplateRemoteResponse,
    DefaultError,
    Options<DeleteWhatsappTemplateRemoteData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await deleteWhatsappTemplateRemote({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Abre um upload assinado no bucket privado para a mídia
 */
export const prepareWhatsappTemplateAssetUploadMutation = (
  options?: Partial<Options<PrepareWhatsappTemplateAssetUploadData>>,
): UseMutationOptions<
  PrepareWhatsappTemplateAssetUploadResponse,
  DefaultError,
  Options<PrepareWhatsappTemplateAssetUploadData>
> => {
  const mutationOptions: UseMutationOptions<
    PrepareWhatsappTemplateAssetUploadResponse,
    DefaultError,
    Options<PrepareWhatsappTemplateAssetUploadData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await prepareWhatsappTemplateAssetUpload({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Confere o arquivo enviado e gera o handle de upload da Meta
 */
export const confirmWhatsappTemplateAssetUploadMutation = (
  options?: Partial<Options<ConfirmWhatsappTemplateAssetUploadData>>,
): UseMutationOptions<
  ConfirmWhatsappTemplateAssetUploadResponse,
  DefaultError,
  Options<ConfirmWhatsappTemplateAssetUploadData>
> => {
  const mutationOptions: UseMutationOptions<
    ConfirmWhatsappTemplateAssetUploadResponse,
    DefaultError,
    Options<ConfirmWhatsappTemplateAssetUploadData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await confirmWhatsappTemplateAssetUpload({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getWhatsappTemplateAssetPreviewQueryKey = (
  options: Options<GetWhatsappTemplateAssetPreviewData>,
) =>
  createQueryKey('getWhatsappTemplateAssetPreview', options, false, [
    'WhatsAppTemplates',
  ])

/**
 * Devolve uma URL assinada curta para pré-visualizar a mídia
 */
export const getWhatsappTemplateAssetPreviewOptions = (
  options: Options<GetWhatsappTemplateAssetPreviewData>,
) =>
  queryOptions<
    GetWhatsappTemplateAssetPreviewResponse,
    DefaultError,
    GetWhatsappTemplateAssetPreviewResponse,
    ReturnType<typeof getWhatsappTemplateAssetPreviewQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWhatsappTemplateAssetPreview({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getWhatsappTemplateAssetPreviewQueryKey(options),
  })
